### PR TITLE
fix(trading): game results

### LINKED ISSUE #6064: Game resuts on team profile page not working
## The Chore

Run query below ... you will see this team has been in games;

```
query gameDetails {
  games(epochFrom:13280, teamId:"7b704d16f4d0362357251bb9e9782c3d4124f245b45ea3362f2b268c4a343dd6"){
    edges{
      node{
        id
        rewardAssetId
        epoch
        numberOfParticipants
        entities{
          ...on TeamGameEntity{
            team{
              teamId
            }
            rank
            volume
            rewardMetric
            rewardEarned
            rewardEarnedQuantum
            totalRewardsEarned
            totalRewardsEarnedQuantum
          }
        }
      }
    }
  }
```

Open team profile page for that team here: 
https://vegafairground.eth.limo/#/competitions/teams/7b704d16f4d0362357251bb9e9782c3d4124f245b45ea3362f2b268c4a343dd6

You will see that no results are shown.

image

## Tasks

- [ ] Fix it 
- [ ] Test it

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes #6064

# Description ℹ️

* "from 0 to hero"

# Demo 📺

image

# Technical 👨‍🔧

* games query segmentation into blocks of max 30 epochs

### CODE REVIEW

File: apps/trading/lib/hooks/use-games.ts [hunk 1]
```diff
@@ -42,35 +92,75 @@ export const useGames = (teamId?: string, epochFrom?: number): GamesData => {
...
+      const currentEpoch = Number(epochData.epoch.id);
+      from = currentEpoch - TEAMS_STATS_EPOCHS;
+      to = currentEpoch;
+    }
+
+    if (!from) return [];
+    return prepareVariables(teamId, from, to);
+  }, [epochData?.epoch.id, epochFrom, epochTo, teamId]);
+
+  useEffect(() => {
```
Comment (mattrussell36) [inline apps/trading/lib/hooks/use-games.ts:115]: @asiaznik can we get a comment here explaining why are dynamically creating a bunch of queries, rather than using the API in the expected way

**Review by bwallacee — APPROVED** [review]

**Review by mattrussell36 — APPROVED** [review]

**Review by MadalinaRaicu — APPROVED** [review]
