### PR TITLE
fix: 1569 navigation link active on market selected refresh

### LINKED ISSUE #1569: Trading tab inconsistent behaviour
The trading tab should let the user navigate to the last viewed market. 

This isn’t working because we only get your last viewed market from local storage when you visit the home page initially or select it from the dropdown (edited) 

If you navigate directly to the portfolio page this never happens so when you click trading there's no cached market.
There is a fallback in place where if that happens you just go to the full list (edited) 

We just need to ensure we set the last viewed market directly in the global store initialization or do it in _app

This can be a fix, though its possible we get hydration errors
```
export const useGlobalStore = create<GlobalStore>((set) => ({
  ...
  marketId: LocalStorage.getItem('the-key'),
  update: (state) => {
    set(state);
  },
}));
```

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #1569 

# Description ℹ️

When refresh after market is selected, Trading tab does not seem to be active/highlighted. 

# Demo 📺 & Technical 👨‍🔧

image

### CODE REVIEW

File: apps/trading/components/navbar/navbar.tsx [hunk 1]
```diff
@@ -59,7 +52,7 @@ interface NavLinkProps {
 
 const NavLink = ({ name, path, testId = name }: NavLinkProps) => {
   const router = useRouter();
-  const isActive = router.asPath === path;
+  const isActive = router.asPath.includes(path);
```
Comment (MadalinaRaicu) [inline apps/trading/components/navbar/navbar.tsx:55]: sth weird happening here. it works for the trading tab but i should not be doing this. fails on the portfolio tab after refresh.

File: apps/trading/components/navbar/navbar.tsx [hunk 2]
```diff
@@ -59,7 +58,11 @@ interface NavLinkProps {
 
 const NavLink = ({ name, path, testId = name }: NavLinkProps) => {
   const router = useRouter();
-  const isActive = router.asPath === path;
+  const [isActive, setIsActive] = useState(false);
```
Comment (MadalinaRaicu) [inline apps/trading/components/navbar/navbar.tsx:61]: Fixing hydration error. By calling `setIsActive` in `useEffect` a render is triggered after hydrating. https://nextjs.org/docs/messages/react-hydration-error

**Review by macqbat — APPROVED** [review]
