### PR TITLE
fix(markets): back with updating by grid api

### LINKED ISSUE #4058: market list loses visibility of context menu
## Description

Redundant rerenders cause unwanted closing of contextual row menu

## Steps to Reproduce

1. Go to market list
2. Click on any row menu button for open it
3. Menu is open, wait a couple of seconds
4. See error: menu is closed by itself :-(

## Expected behavior

Menu should keep open state

## Screenshots

-

## Device details

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### PR DESCRIPTION
**Pull request by macqbat**
# Related issues 🔗

Closes #4058 

# Description ℹ️

Let's make update of grid data direct by api to prevent re-renders which cause closing open context menu

# Demo 📺

-

# Technical 👨‍🔧

-

### CODE REVIEW

File: libs/markets/src/lib/components/markets-container/markets-container.tsx [hunk 1]
```diff
@@ -30,11 +40,14 @@ export const MarketsContainer = ({ onSelect }: MarketsContainerProps) => {
     };
   }, [reload]);
 
+  const handleOnGridReady = useCallback(() => {
```
Comment (mattrussell36) [inline libs/markets/src/lib/components/markets-container/markets-container.tsx:43]: suggestion (blocking): just tried out using useMemo to create col defs. This fixes the issue and is more simple

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/markets/src/lib/components/markets-container/markets-container.tsx (hunk 1 above)
Comment (mattrussell36) [reply libs/markets/src/lib/components/markets-container/markets-container.tsx:43]: you can merge this change

Comment (macqbat) [reply libs/markets/src/lib/components/markets-container/markets-container.tsx]: merged and little bit improved

**Review by mattrussell36 — APPROVED** [review]
