### PR TITLE
fix(trading): asset option on mobile got overflown

### LINKED ISSUE #2770: Deposit and Withdraw popup and asset dropdown on mobile view don't fit the screen
## Description

Deposit and Withdraw popup and asset dropdown on mobile view don't fit the screen

## Steps to Reproduce
Check on mobile or switch browser to the mobile view.

1. Go to portfolio
2. Click on deposit
4. Popup on mobile view doesn't  fit the screen. Also asset dropdown don't fit the screen

## Expected behavior
Popup on mobile view  fit the screen

## Screenshots
Screenshot 2023-01-28 at 09 00 21
Screenshot 2023-01-28 at 08 58 36

https://user-images.githubusercontent.com/119658839/215455484-f47d2773-cea8-4f19-acea-b66811182f8c.mov

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes #2770 

# Demo 📺

image

### CODE REVIEW

File: libs/assets/src/lib/asset-option.tsx [hunk 1]
```diff
@@ -0,0 +1,15 @@
+import { Option } from '@vegaprotocol/ui-toolkit';
+import type { AssetFieldsFragment } from './__generated__/Asset';
+
+export const AssetOption = ({ asset }: { asset: AssetFieldsFragment }) => {
+  return (
+    <Option key={asset.id} value={asset.id}>
+      <div className="flex flex-col items-start">
+        <span>{asset.name}</span>
+        <div className="text-[10px] font-mono w-full text-left break-all">
```
Comment (edd) [inline libs/assets/src/lib/asset-option.tsx:9]: **praise (non-blocking)**: I've just put the same `break-all` in the block explorer - previously these were `overflow: scroll` but I much prefer this behaviour too

**Review by edd — APPROVED** [review]
