### PR TITLE
fix(governance): handle null validator scores properly

### LINKED ISSUE #5191: The validator penalties dont disntinguish between NULL and actually zero
## The Chore

The validator scoring relies quite heavily on the rewardScore part of the epochs API. 

But if you are a candidate (pending) validator this part is null as below.

image

This means the scores for Candidate validators are always misleading 
image

And it means in the first epoch after promotion the scores for Standby validators are misleading
image

## Tasks

- [ ] For Candidate validators
  - [ ] Set total penalties to "-" as rewardScore will always be null so there is no validatorScore to use
  - [ ] Set overstaking penalty to  "-" because it requires the rawValidatorScore from rewardScore so will always be null
  - [ ] Performance penalty should be ok because it is taken from rankingScore in current epoch and this is never null

- [ ] For Standby validators 
  - [ ] If rewardScore is null then apply treatment as above
  - [ ] Else calculate scores as usual

### PR DESCRIPTION
**Pull request by edd**
# Related issues 🔗

Closes #5191

# Description ℹ️

Properly handle null values when calculating total and other penalties. It's not totally clear to me why the value in the test changes, but it seems correct to me.

# Demo 📺

Screenshot 2023-12-06 at 12 28 02

### CODE REVIEW

**Review by MadalinaRaicu — APPROVED** [review]

File: apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx [hunk 1]
```diff
@@ -153,14 +162,12 @@ export const StandbyPendingValidatorsTable = ({
...
-              2
-            ),
-            [ValidatorFields.TOTAL_PENALTIES]: formatNumberPercentage(
-              calculateOverallPenalty(id, allNodesInPreviousEpoch),
-              2
-            ),
+            [ValidatorFields.OVERSTAKING_PENALTY]: overstakingPenalty
+              ? formatNumberPercentage(overstakingPenalty, 2)
+              : '-',
+            [ValidatorFields.TOTAL_PENALTIES]: totalPenalty
```
Comment (asiaznik) [inline apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx:168]: **nitpick**: all of this could be handled inside `formatNumberPercentage`

File: apps/governance/src/routes/staking/shared.ts [hunk 2]
```diff
@@ -37,19 +41,30 @@ const calculateTheoreticalStakeScore = (nodeId: string, nodes: Node[]) => {
 };
 
 /**
- * Calculates overall penalty for a given node
+ * Calculates overall penalty for a given nodsadase
```
Comment (asiaznik) [inline apps/governance/src/routes/staking/shared.ts:44]: **new word warning** 🥲 Say `nodsadase` one more time, I dare you. @#$% 🔫

File: apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx (hunk 1 above)
Comment (edd) [reply apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx:168]: Making this change was the right move, but revealed some failing tests in develop! I blame you!

**Review by MadalinaRaicu — APPROVED** [review]

**Review by MadalinaRaicu — APPROVED** [review]

**Review by MadalinaRaicu — APPROVED** [review]

**Comment by edd** [comment]
@vegaprotocol/frontend-qa my memory is that we agreed that this is hard to test, so we should just merge it? I don't mind being told no - but if that isn't the case, how can we make this mergeable?

**Review by bwallacee — APPROVED** [review]

**Comment by edd** [comment]
Waiting for #5646 to be merged before this can be merged. Out of politeness, not a technical reason.
