### PR TITLE
fix: flickering

### LINKED ISSUE #2441: Flickering validators list on token app
## Description

The list of validators on the staking tab of the token website is flickering when loading.

## Steps to Reproduce

1. Go to token.vega.xyz
2. Click on staking
3. Scroll not
4. See list flickering

## Expected behavior

No flickerin

## ~Screenshots~ Recording

https://user-images.githubusercontent.com/4346460/208723876-2682438c-dfdf-4419-be7e-595efa6e1fb6.mov

## Device details

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox
- Version: 107.0.1

### PR DESCRIPTION
**Pull request by dexturr**
# Related issues 🔗

Closes #2441 

# Description ℹ️

Prevent flcikering in some cases of the validators table.

# Technical 👨‍🔧

We are loading 2 sets of data, which created a race condition, causing flickering.

### CODE REVIEW

File: apps/token/src/routes/staking/home/validator-tables/validator-tables.tsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ export const ValidatorTables = ({
             case Schema.ValidatorStatus.VALIDATOR_NODE_STATUS_PENDING:
               acc.pendingValidators.push(validator);
           }
-
+          console.log(data?.nodesConnection.edges);
```
Comment (dexturr) [inline apps/token/src/routes/staking/home/validator-tables/validator-tables.tsx:62]:
```suggestion
```

**Review by mattrussell36 — APPROVED** [review]
