### PR TITLE
fix(1758): data node being down

### LINKED ISSUE #1758: The default data node URL being down should not crash the site
On Sunday the mainnet observer data node went down. This is the one hosted and run by Vega as is the one that is the default to connect to on the token site. This resulted in the site being unable to load for minutes at a time.

This should not be the case and the node switcher dialog should show up as quickly as possible to allow the user to select or enter a different data node as soon as it is apparent the default is not working.

### PR DESCRIPTION
**Pull request by dexturr**
# Related issues 🔗

Closes #1758

# Description ℹ️

The data node being down caused the site to be inoperable. This was due to the request hanging and there being no timeout on the frontends, this is true for all requests. This means that any request hanging could potentially cause the whole site to become inoperable.

# Technical

I needed to add the timeout link for data nodes, as requests hanging would bring any site to a stop. This made me realise that we were duplicating a LOT of code in the apollo client files. I have inverted the cache policy dependency so the consumers can specify it themselves.

### CODE REVIEW

File: libs/apollo-client/src/lib/apollo-client.ts [hunk 1]
```diff
@@ -11,18 +12,19 @@ import { getMainDefinition } from '@apollo/client/utilities';
...
+export function createClient(base?: string, cacheConfig?: InMemoryCacheConfig) {
   if (!base) {
     throw new Error('Base must be passed into createClient!');
   }
   const urlHTTP = new URL(base);
   const urlWS = new URL(base);
   // Replace http with ws, preserving if its a secure connection eg. https => wss
   urlWS.protocol = urlWS.protocol.replace('http', 'ws');
-
+  const timeoutLink = new ApolloLinkTimeout(5000);
```
Comment (dexturr) [inline libs/apollo-client/src/lib/apollo-client.ts:27]: question: What should this be? I am not married to this, but felt "good enough"

Comment (dexturr) [inline libs/apollo-client/src/lib/apollo-client.ts:27]:
```suggestion
  const timeoutLink = new ApolloLinkTimeout(10000);
```

File: apps/token/src/app.tsx [hunk 2]
```diff
@@ -26,9 +26,148 @@ import {
...
+    Query: {
+      fields: {
+        nodes: {
+          // Merge function to make the validator list random but remain consistent
+          // as the user navigates around the site. If the user refreshes the list
+          // will be randomised.
+          merge: (existing = [], incoming) => {
+            // uniqBy will take the first of any matches
+            const uniq = uniqBy([...incoming, ...existing], 'id');
+            // sort result so that the input is consistent
```
Comment (sam-keen) [inline apps/token/src/app.tsx:71]: Question (non-blocking): why is it important the the input is consistent?

**Review by sam-keen — APPROVED** [review]

File: apps/token/src/app.tsx [hunk 3]
```diff
@@ -26,9 +26,148 @@ import {
...
+  InMemoryCacheConfig,
+  Reference,
+} from '@apollo/client';
+import sortBy from 'lodash/sortBy';
+import uniqBy from 'lodash/uniqBy';
+
+import { deterministicShuffle } from './lib/deterministic-shuffle';
+import { addDecimal } from '@vegaprotocol/react-helpers';
+
+const formatUintToNumber = (amount: string, decimals = 18) =>
```
[the remark this answers is not in the document]
Comment (dexturr) [reply apps/token/src/app.tsx:42]: Yeah it is, I want to get rid of this anyway so I will create a ticket for that :+1:

File: apps/token/src/app.tsx (hunk 2 above)
Comment (dexturr) [reply apps/token/src/app.tsx:71]: So this was a random requirement, the valdiators wanted the list to be randomised before the scoring mechanism was introduced. But we wanted to persist that across a user session so the table didn't jump around on update. This is the fix for that, when we do the validator table improvements my hope is we can kill this 🙏

Comment (dexturr) [reply apps/token/src/app.tsx:71]: Or possibly have we already sorted the table and this can go now?

File: apps/token/src/app.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (dexturr) [reply apps/token/src/app.tsx:42]: https://github.com/vegaprotocol/frontend-monorepo/issues/2015
