### PR TITLE
fix: deal ticket set market price

### LINKED ISSUE #2071: Deal ticket doesn't receive latest market and account data
## Description

The deal ticket relies on some market and account data. For example market states and trading modes for validation, and account data for showing your balance and estimated margin requirements. However, it doesn't stay up to date via a subscription or otherwise.

## Steps to Reproduce

1. Go to the deal ticket with a public key that doesn't have any collateral
2. Try to submit and order and you will get a validation message saying 0 balance
3. Deposit some of the required asset
4. Try to place the order again and the you will still get the 0 balance validation message

## Additional context

This is likely because the deal ticket makes its own query for market state and doesn't use the market provider. And equally it uses a hook `usePartyBalanceQuery` rather than an accounts provider.

### LINKED ISSUE #2137: Deal ticket does not update limit and market price anymore
It is only on develop branch now.

Deal ticket does not update the price anymore when switching from Limit to Market. 

1. Switch to Limit
2. Populate with a different price than the market price
3. Switch back to Market and you can see the estimates do not update
4. If you refresh, limit price is saved in local storage so estimates still don't update. 

This would be a regression bug. 

Image

Image

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #2137 

# Description ℹ️

Deak ticket price and estimates do not update on the order type switch. 

# Demo 📺

image

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

File: libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx [hunk 1]
```diff
@@ -63,6 +65,14 @@ export const DealTicket = ({
   const order = watch();
   // When order state changes persist it in local storage
   useEffect(() => setPersistedOrder(order), [order, setPersistedOrder]);
+
+  // When switch back to market order, set price to market price
+  useEffect(() => {
```
Comment (mattrussell36) [inline libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx:70]: chore (blocking): can you show me why we need this? The order estimate query now gets the correct price directly from market.data.markPrice or market.data.indicativePrice (or order.price if limit order).

This also results in loss of state of your user input limit order price see below:

Uploading Nov-24-2022 16-13-07.mp4…

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx (hunk 1 above)
Comment (mattrussell36) [reply libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx:70]: I see where the issue is. Will push a fix

**Review by mattrussell36 — APPROVED** [review]
