### PR TITLE
feat: [console-lite] - fixes in order margin calcs

### LINKED ISSUE #890: Fixes and tweaks for order margin calculation
## Task
Fix spotted issues, add possible improvements to the process of calculating initial order margin in console-lite

## ACs

- [x] Fix casting BigNumber balance to bool by use method `isZero` instead in `useMarketPositions`
- [x] Remove some typos and console.logs
- [x] Consider get rid off a call to estimateOrder since it calculates only order's size & price & market risk factor, and it's roughly possible to do it on only market data

### PR DESCRIPTION
**Pull request by macqbat**
# Related issues 🔗

Closes #890 890
# Description ℹ️

Fix spotted issues, add possible improvements to the process of calculating initial order margin in console-lite

### CODE REVIEW

File: apps/simple-trading-app/src/app/hooks/use-order-margin.ts [hunk 1]
```diff
@@ -66,41 +66,30 @@ const types: Record<VegaWalletOrderType, OrderType> = {
...
         0,
-        new BigNumber(
-          addDecimal(
-            data.estimateOrder.marginLevels.initialLevel,
-            market.decimalPlaces
-          )
-        )
-          .minus(marketPositions?.balanceSum.toNumber() || 0)
+        new BigNumber(data.estimateOrder.marginLevels.initialLevel)
+          .minus(marketPositions?.balance || 0)
```
Comment (bglownia) [inline apps/simple-trading-app/src/app/hooks/use-order-margin.ts:92]: it should be toString, toNumber reach Number.MAX_SAFE_INTEGER

**Review by bglownia — APPROVED** [review]

File: apps/simple-trading-app/src/app/hooks/use-order-margin.ts (hunk 1 above)
Comment (macqbat) [reply apps/simple-trading-app/src/app/hooks/use-order-margin.ts]: done

**Review by elmar-vega — APPROVED** [review]
