### PR TITLE
fix(trading): remove price flash cell from PNL

### LINKED ISSUE #2826: Remove flash cell from PNL cells
## Description

The PNL cells are already rendered green or red depending on profit/loss having the cell text change color when it goes up or down is confusing as you might have a profitable position that suddenly renders in red for a moment before going back to green.

## Steps to Reproduce

1. Place a trade to open a position
2. Observe the realised PNL cell
3. Keep observing... :-)
4. Eventually you will see it flash red if your PNL goes down

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #2826 

# Description ℹ️

 Remove price flash cell from PNL 

# Demo 📺

Gif/video/images of new/corrected functionality if applicable

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

File: libs/positions/src/lib/positions-table.tsx [hunk 1]
```diff
@@ -360,7 +360,7 @@ export const PositionsTable = forwardRef<AgGridReact, Props>(
               ? undefined
               : addDecimalsFormatNumber(data.unrealisedPNL, data.decimals)
           }
-          cellRenderer="PriceFlashCell"
+          cellRenderer="PriceCell"
```
Comment (mattrussell36) [inline libs/positions/src/lib/positions-table.tsx:363]: chore (blocking): You need to add PriceCell to the components prop of the AgGrid component

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/positions/src/lib/positions-table.tsx (hunk 1 above)
Comment (MadalinaRaicu) [reply libs/positions/src/lib/positions-table.tsx:364]: updated

**Review by mattrussell36 — APPROVED** [review]
