### PR TITLE
fix: deal ticket fees value formatting

### LINKED ISSUE #2002: Incorrect decimal used on estimate order response
## Description

The wrong decimal is used on the response from estimate order. This endpoint use market decimal for price and position market decimal for size, then returns all amounts in Asset decimal.

The front end needs to apply the asset decimals on the returned results (fees and margins)

## Steps to Reproduce

1. Go to stagnet1 console
2. Click on deal ticket
3. enter price and size
4. See the returned margins and fee, it's wrong

## Expected behavior

The amount displayed should be scaled using asset decimal

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #2002 

# Description ℹ️

Format estimate order query results with asset dp after core version v0.62.0

### CODE REVIEW

File: libs/deal-ticket/src/hooks/use-fee-deal-ticket-details.tsx [hunk 1]
```diff
@@ -96,21 +96,38 @@ export const getFeeDetailsValues = ({
...
 }: FeeDetails) => {
-  const formatValue = (value: string | number | null | undefined): string => {
+  const formatValueWithMarketDp = (
+    value: string | number | null | undefined
+  ): string => {
     return value && !isNaN(Number(value))
-      ? normalizeFormatNumber(value, market.decimalPlaces)
+      ? normalizeFormatNumber(
+          value,
+          market.tradableInstrument.instrument.product.settlementAsset.decimals
```
Comment (MadalinaRaicu) [inline libs/deal-ticket/src/hooks/use-fee-deal-ticket-details.tsx:105]:
```suggestion
          market.decimalPlaces
```

**Review by mattrussell36 — APPROVED** [review]
