### PR TITLE
fix(#2200): handle NotFound GraphQL errors in async renderer

### LINKED ISSUE #2200: [console] NotFound error handling
Core has made API changes where not found resources return an error object (with type `NotFound`). Our error handling is often crudely just checking for the presence of an error object when we should also be checking the error type and handling it differently.

## Tasks

- [x] Update AsyncRenderer to handle NotFound errors
- [x] Review usage of errors returned from data providers, useQuery hooks, and useGeneratedQuery hooks and update error handling accordingly
- [x] Update apollo client error link to not report not found errors

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #2200 

# Description ℹ️ &  Technical 👨‍🔧

- [x] handle NotFound GraphQL errors in the async renderer
- [x] handle NotFound GraphQL errors in certain queries / data providers
- [x] add method in apollo-client to spot NotFound errors but not filter them

# Demo 📺

Handles this issue observed in empty stagnet3: 

Screenshot 2022-11-22 at 10 02 00

Screenshot 2022-11-23 at 08 26 22

### CODE REVIEW

File: libs/positions/src/lib/positions-manager.tsx [hunk 1]
```diff
@@ -25,7 +25,13 @@ export const PositionsManager = ({ partyId }: PositionsManagerProps) => {
 
   return (
     <>
-      <AsyncRenderer loading={loading} error={error} data={data}>
+      <AsyncRenderer
```
Comment (MadalinaRaicu) [inline libs/positions/src/lib/positions-manager.tsx:28]: it was displaying `No data` and it was inconsistent with the other tabs. (regression)

Comment (MadalinaRaicu) [inline libs/positions/src/lib/positions-manager.tsx:28]: it was displaying `No data` and it was inconsistent with the other tabs. (regression)

File: libs/ui-toolkit/src/components/splash/splash.tsx [hunk 2]
```diff
@@ -7,7 +7,7 @@ export interface SplashProps {
 
 export const Splash = ({ children }: SplashProps) => {
   const splashClasses = classNames(
-    'w-full h-full',
+    'w-full h-full text-xs text-center text-gray-200',
```
Comment (MadalinaRaicu) [inline libs/ui-toolkit/src/components/splash/splash.tsx:10]: aligning style of ag-grid overlay and splash classes

File: libs/fills/src/lib/fills-manager.tsx [hunk 3]
```diff
@@ -29,7 +29,12 @@ export const FillsManager = ({ partyId }: FillsManagerProps) => {
   };
 
   return (
-    <AsyncRenderer loading={loading} error={error} data={data}>
+    <AsyncRenderer
```
Comment (MadalinaRaicu) [inline libs/fills/src/lib/fills-manager.tsx:32]: allow overlay of ag-grid to be displayed.

File: libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx [hunk 4]
```diff
@@ -46,7 +46,7 @@ export const DealTicketMarketAmount = ({
       <div className="flex items-end gap-4 mb-2">
         <div className="flex-1 text-sm">Size</div>
         <div />
-        <div className="flex-1 text-sm text-right">
+        <div className="flex-2 text-sm text-right">
```
Comment (MadalinaRaicu) [inline libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx:49]: unwrap `Estimated uncrossing price`

File: libs/apollo-client/src/lib/apollo-client.ts [hunk 5]
```diff
@@ -61,12 +64,34 @@ export function createClient(base?: string, cacheConfig?: InMemoryCacheConfig) {
...
+    }
   });
 
   return new ApolloClient({
     link: from([errorLink, timeoutLink, retryLink, splitLink]),
     cache: new InMemoryCache(cacheConfig),
   });
 }
+
+const isApolloGraphQLError = (
```
Comment (mattrussell36) [inline libs/apollo-client/src/lib/apollo-client.ts:81]: question (non blocking): Why do we need this type guard?  `graphqlErrors` is already typed as `GraphqlErrors | undefined` so shouldn't a simple undefined check should suffice?

File: libs/apollo-client/src/lib/apollo-client.ts [hunk 6]
```diff
@@ -61,12 +64,34 @@ export function createClient(base?: string, cacheConfig?: InMemoryCacheConfig) {
     : httpLink;
 
   const errorLink = onError(({ graphQLErrors, networkError }) => {
-    if (graphQLErrors) console.log(graphQLErrors);
-    if (networkError) console.log(networkError);
+    if (graphQLErrors && !hasNotFoundGraphQLErrors(graphQLErrors)) {
```
Comment (mattrussell36) [inline libs/apollo-client/src/lib/apollo-client.ts:67]: chore (blocking): If graphqlErrors contains a mix of NotFound errors and legitimate errors this check will now prevent the legitimate errors from being logged. Can we change this so we filter out any NotFound errors and still log any remaining errors?

File: libs/react-helpers/src/hooks/use-data-provider.ts [hunk 7]
```diff
@@ -85,7 +86,7 @@ export const useDataProvider = <
         isInsert,
         isUpdate,
       } = args;
-      setError(error);
+      setError(isNotFoundGraphQLError(error) ? undefined : error);
```
Comment (mattrussell36) [inline libs/react-helpers/src/hooks/use-data-provider.ts:89]: chore (blocking): I'd revert this, the data provider should still return any error it sees, it should be up to the application/component to decide how to handle it

File: libs/ui-toolkit/src/components/splash/splash.tsx (hunk 2 above)
Comment (mattrussell36) [reply libs/ui-toolkit/src/components/splash/splash.tsx:10]: Have you checked both light and dark themes here?

File: libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx (hunk 4 above)
Comment (mattrussell36) [reply libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx:49]: To me it looks nicer if the text is contained to an equal portion of the flex container, even if it wraps. If there is enough space it will unwrap.

Below the text flowing outside of the 'grid' and into the left sides space looks off to me as it disrupts the alignment the inputs below

Screen Shot 2022-11-23 at 19 21 11

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/apollo-client/src/lib/apollo-client.ts (hunk 5 above)
Comment (MadalinaRaicu) [reply libs/apollo-client/src/lib/apollo-client.ts:81]: won't compile unless `error is ApolloError`

File: libs/apollo-client/src/lib/apollo-client.ts (hunk 6 above)
Comment (MadalinaRaicu) [reply libs/apollo-client/src/lib/apollo-client.ts]: sure, updated in last commit.

File: libs/react-helpers/src/hooks/use-data-provider.ts (hunk 7 above)
Comment (MadalinaRaicu) [reply libs/react-helpers/src/hooks/use-data-provider.ts]: agree!!! updated in last commit.

**Review by mattrussell36 — APPROVED** [review]
