### PR TITLE
fix(positions): make positions table smoothly updated (again)

### LINKED ISSUE #3265: positions table: close buttons blink
## The Bug

After recent change from infinitive to clientSide model close buttons in position rows blink when updating :-(
We need to tweak. `update` and `insert` param methods for use ag-grid `api.applyTransaction` though

## Tasks

- [ ] manage to use ag-grid api applyTransaction

### PR DESCRIPTION
**Pull request by macqbat**
# Related issues 🔗

Closes #3265

# Description ℹ️

Use ag-grid model api method for update content of the grid

# Demo 📺

-

# Technical 👨‍🔧

-

### CODE REVIEW

File: libs/positions/src/lib/use-positions-data.tsx [hunk 1]
```diff
@@ -21,9 +21,31 @@ export const usePositionsData = (
   const dataRef = useRef<Position[] | null>(null);
   const update = useCallback(
     ({ data }: { data: Position[] | null }) => {
-      return clientSideModel ? false : updateGridData(dataRef, data, gridRef);
+      console.log('update data', data);
```
Comment (mattrussell36) [inline libs/positions/src/lib/use-positions-data.tsx:24]: chore (blocking): remove log

**Review by mattrussell36 — DISMISSED** [review]

File: libs/positions/src/lib/use-positions-data.tsx (hunk 1 above)
Comment (macqbat) [reply libs/positions/src/lib/use-positions-data.tsx]: done

**Review by asiaznik — APPROVED** [review]
