### PR TITLE
fix: orderbook decimal formats

### LINKED ISSUE #859: Review all decimal places in Console (except market info)
This to conduct a review all decimal places (asset decimal, market decimal, position decimal, tick size etc). Document how they all relate and build rules into UI's to show them correctly.

There are 4 definitions of the number of decimal places 

- `Asset.decimals`
- `Market.decimalPlaces`
- `Market.positionDecimalPlaces`
- `settlementPriceDecimals`

Generally:

- `Asset.decimals` should alway match the asset on the native chain. e.g. for ERC20 it is often 18.
- `Market.decimalPlaces` is the number of decimal places for the Quote. e.g if it is BTC/USD it'll be how precise you can quote BTC in USD. .e.g 5 (USD may be the asset DAI which has 18 DP)
- `Market.positionDecimalPlaces` is the size field on a order/position and the Volume in the order book. note on Testnet this has only ever been 0. if it we more than zero we'd be using the new fractional order sizes
- `settlementPriceDecimals` used for oracle price (not displayed anywhere in console).

Notes:
- Accounts are always asset.decmals
- the limit price is always `Market.decimalPlaces`
- the size is always `Market.positionDecimalPlaces`
- market decimal places and tick size are very related as it tells you how much there is between each possible price on the market
- oracle price used for settlement in oracle spec = `settlementPriceDecimals` 

Where each should be used:
## Chart
- y axis should use `Market.decimalPlaces`

## Depth chart
- X axis `Market.decimalPlaces`
- Y axis `Market.positionDecimalPlaces`

## Ticket 
- Amount (aka size): use  `Market.positionDecimalPlaces`
- the price next to amount on market order or input on Limit order: `Market.decimalPlaces`

## info
This is going to go into a separate ticket

## Order book 
- bid and ask vol = `Market.positionDecimalPlaces`
- cumulative vol = `Market.positionDecimalPlaces`
- price = `Market.decimalPlaces`

## Trades
- price = `Market.decimalPlaces`
- size = `Market.positionDecimalPlaces`

## Positions 
Screenshot 2022-07-27 at 13 48 52

new table:

image
https://github.com/vegaprotocol/frontend-monorepo/issues/840

- amount aka size: `Market.positionDecimalPlaces`
- Avg entry price: `Market.decimalPlaces`
- mark price: `Market.decimalPlaces`
- liquidation price `Market.decimalPlaces`
- leverage = n/a
- margin allocated = `Asset.decimals`
- PnL = `Asset.decimals`

## Orders
- amount (aka size) : `Market.positionDecimalPlaces`
- Filled =  `Market.positionDecimalPlaces`
- Price = `Market.decimalPlaces`
- Mark price = `Market.decimalPlaces`
- pNL: `asset.decimals` (this assumes PnL is not rounded) ACTION: check rounding.

## Collateral 
- All `asset.decimals`

## Fills 
This table needs a number of changes do have commented decimals on this ticket:  
https://github.com/vegaprotocol/frontend-monorepo/issues/845#issuecomment-1203789356

### PR DESCRIPTION
**Pull request by notbot00**
# Related issues 🔗

Closes #859 

# Description ℹ️

#### Chart
- [x] y axis should use `Market.decimalPlaces`

#### Depth chart
- [x] X axis `Market.decimalPlaces`
- [x] Y axis `Market.positionDecimalPlaces` (changed in this PR, based on: https://github.com/vegaprotocol/pennant/issues/541)

#### Ticket 
- [x] Amount (aka size): use  `Market.positionDecimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/deal-ticket/src/components/deal-ticket.tsx#L47)
- [x] the price next to amount on market order or input on Limit order: `Market.decimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/deal-ticket/src/components/deal-ticket.tsx#L84-L97)

#### Order book 
- [x] bid and ask vol = `Market.positionDecimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/market-depth/src/lib/orderbook-row.tsx#L43-L49)
- [x] cumulative vol = `Market.decimalPlaces` (apparently also already correct)
- [x] price = `Market.positionDecimalPlaces` (apparently also already correct)

#### Trades
- [x] price = `Market.decimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/trades/src/lib/trades-table.tsx#L60-L76)
- [x] size = `Market.positionDecimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/trades/src/lib/trades-table.tsx#L77-L93)

#### Positions 
- [x] changes in https://github.com/vegaprotocol/frontend-monorepo/pull/902 seem all correct

#### Orders
- [x] amount (aka size) : `Market.positionDecimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/orders/src/lib/components/order-list/order-list.tsx#L116-L134)
- [x] filled =  `Market.positionDecimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/orders/src/lib/components/order-list/order-list.tsx#L155-L177)
- [x] price = `Market.decimalPlaces` (already correct: https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/orders/src/lib/components/order-list/order-list.tsx#L178-L197)
- [ ] mark price = `Market.decimalPlaces` (not found in orders)
- [ ] PnL: `asset.decimals` (this assumes PnL is not rounded) ACTION: check rounding. (not found in orders)

#### Collateral 
- [x] all `asset.decimals` (already correct - only balance field is the only numeric field to be formatted - https://github.com/vegaprotocol/frontend-monorepo/blob/master/libs/accounts/src/lib/accounts-table.tsx#L131-L141)

### CODE REVIEW

File: libs/positions/src/lib/positions-table.tsx [hunk 1]
```diff
@@ -153,9 +153,19 @@ export const PositionsTable = forwardRef<AgGridReact, PositionsTableProps>(
             'color-vega-red': ({ value }: { value: string }) =>
               Number(value) < 0,
           }}
-          valueFormatter={({ value, data }: ValueFormatterParams) =>
```
Comment (bglownia) [inline libs/positions/src/lib/positions-table.tsx:156]: positions-table is totally changed in #473, PR is waiting for review

File: libs/market-depth/src/lib/orderbook-row.tsx [hunk 2]
```diff
@@ -43,19 +43,19 @@ export const OrderbookRow = React.memo(
         <Vol
           testId={`bid-vol-${price}`}
           value={bid}
-          valueFormatted={addDecimal(bid, positionDecimalPlaces)}
+          valueFormatted={addDecimal(bid, decimalPlaces)}
```
Comment (mattrussell36) [inline libs/market-depth/src/lib/orderbook-row.tsx:46]: question (blocking): Are you sure these three changes are correct? My understanding is that price values should use market.decimalPlaces, and volume/size should use market.positionDecimalPlaces (for fractional order sizes)

Comment (campbellssource) [reply libs/market-depth/src/lib/orderbook-row.tsx:46]: That's on me. I had it wrong in the ticket. have corrected it now.

File: libs/positions/src/lib/positions-table.tsx (hunk 1 above)
Comment (notbot00) [reply libs/positions/src/lib/positions-table.tsx]: reverted the position table changes so we don't get conflicts while waiting

File: libs/market-depth/src/lib/orderbook-row.tsx (hunk 2 above)
Comment (notbot00) [reply libs/market-depth/src/lib/orderbook-row.tsx]: changed this to align with the criteria

File: libs/market-depth/src/lib/orderbook-row.tsx [hunk 3]
```diff
@@ -50,12 +50,12 @@ export const OrderbookRow = React.memo(
         <PriceCell
           testId={`price-${price}`}
           value={BigInt(price)}
-          valueFormatted={addDecimalsFormatNumber(price, decimalPlaces)}
+          valueFormatted={addDecimalsFormatNumber(price, positionDecimalPlaces)}
```
Comment (mattrussell36) [inline libs/market-depth/src/lib/orderbook-row.tsx:53]: chore (blocking): Should be market.decimalPlaces for price

File: libs/market-depth/src/lib/orderbook-row.tsx [hunk 4]
```diff
@@ -50,12 +50,12 @@ export const OrderbookRow = React.memo(
...
         />
         <Vol
           testId={`ask-vol-${price}`}
           value={ask}
-          valueFormatted={addDecimal(ask, positionDecimalPlaces)}
+          valueFormatted={addDecimal(ask, decimalPlaces)}
```
Comment (mattrussell36) [inline libs/market-depth/src/lib/orderbook-row.tsx:58]: chore (blocking): should be market.positionDecimalPlaces for volume/size

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/market-depth/src/lib/orderbook-row.tsx (hunk 4 above)
Comment (notbot00) [inline libs/market-depth/src/lib/orderbook-row.tsx:58]:
```suggestion
          valueFormatted={addDecimal(ask, positionDecimalPlaces)}
```

File: libs/market-depth/src/lib/orderbook-row.tsx [hunk 5]
```diff
@@ -50,7 +50,7 @@ export const OrderbookRow = React.memo(
         <PriceCell
           testId={`price-${price}`}
           value={BigInt(price)}
-          valueFormatted={addDecimalsFormatNumber(price, decimalPlaces)}
+          valueFormatted={addDecimalsFormatNumber(price, positionDecimalPlaces)}
```
Comment (notbot00) [inline libs/market-depth/src/lib/orderbook-row.tsx:53]:
```suggestion
          valueFormatted={addDecimalsFormatNumber(price, decimalPlaces)}
```

File: libs/market-depth/src/lib/orderbook-row.tsx (hunk 4 above)
Comment (notbot00) [reply libs/market-depth/src/lib/orderbook-row.tsx]: changed it back

File: libs/market-depth/src/lib/orderbook-row.tsx (hunk 3 above)
Comment (notbot00) [reply libs/market-depth/src/lib/orderbook-row.tsx]: changed it back

File: libs/market-depth/src/lib/depth-chart.tsx [hunk 6]
```diff
@@ -161,7 +162,15 @@ export const DepthChartContainer = ({ marketId }: DepthChartManagerProps) => {
 
   return (
     <AsyncRenderer loading={loading} error={error} data={data}>
-      {depthData && <DepthChart {...depthData} theme={theme} />}
+      {depthData && (
+        <DepthChart
+          {...depthData}
+          theme={theme}
+          volumeFormat={(volume) =>
```
Comment (johnwalley) [inline libs/market-depth/src/lib/depth-chart.tsx:169]: We should also pass a value for `priceFormat`. The chart defaults to 2dp if we don't provide a value.

Comment (notbot00) [reply libs/market-depth/src/lib/depth-chart.tsx:169]: hmm, there are a lot of `formatLevel` function calls going on a few lines above, which seemingly pre-format the prices going in the chart data. are those redundant? not sure i fully understand their purpose

Comment (johnwalley) [reply libs/market-depth/src/lib/depth-chart.tsx:169]: They seem badly named. I'd probably call them `parseLevel` or similar. It looks like they take the raw API data which are strings and converts it to numbers.

Comment (notbot00) [reply libs/market-depth/src/lib/depth-chart.tsx:153]: okay, removed the decimal formatting from the formatLevel function and renamed it to parseLevel

Comment (johnwalley) [reply libs/market-depth/src/lib/depth-chart.tsx:153]: We are surrounded by strangely named functions!

I think we still need `addDecimal` because it converts the string (integer) we get from the API to a string (decimal floating point style, e.g. NNNN.MMMMM). We can then convert this to a number to pass to the chart.

What we could do with is a function that takes the string from the API and returns the corresponding JS number. We might already have one but I can't see it. There is `toBigNum` but the charts don't support it.

(Off topic for this PR but presumably we work with numbers the way we do because we are concerned about precision and accuracy. This should impact the charts too. I'll put some thought into it) 

Now if volume is encoded in the same way we also need to convert that from an integer string to a decimal string.

All of the above is based on my knowledge of the API data schema from last year. It's possible we have changed how we encode numbers in a way which materially affects the charts but I've not seen anything to suggest that.

Comment (notbot00) [reply libs/market-depth/src/lib/depth-chart.tsx:184]: okay, i think i understand what the problem was, namely that the decimalPlaces and the positionDecimalPlaces are different, so to be accurate along the x and y axes we need to have both numeric values using the correct decimals for each. fixed this. not sure what else we're missing in this PR.

**Review by dexturr — APPROVED** [review]

**Review by mattrussell36 — APPROVED** [review]
