### PR TITLE
fix: proposals list

### LINKED ISSUE #2372: Open proposals not displayed on core v.0.64.0
## Description

On latest core release `0.64.0` no open proposal are currently displayed in `/proposals` including newly created proposals

## Steps to Reproduce

1. Create a new proposal (eg freeform proposal) with valid fields and successful submission
2. Now go to proposals by clicking the proposals tab
3. Newly created proposal should be displayed on the page but it is not.

### PR DESCRIPTION
**Pull request by dexturr**
# Related issues 🔗

Closes #2372

# Description ℹ️

Fixes proposal list logic

### CODE REVIEW

File: apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ interface SortedProposalsProps {
 export const ProposalsList = ({ proposals }: ProposalsListProps) => {
   const { t } = useTranslation();
   const [filterString, setFilterString] = useState('');
-
+  console.log(proposals);
```
Comment (sam-keen) [inline apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx:27]: Chore: remove console log

**Review by sam-keen — CHANGES_REQUESTED** [review]

File: apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx (hunk 1 above)
Comment (dexturr) [inline apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx:27]:
```suggestion
```
