### PR TITLE
fix(wallet): fetch new keys without re-connecting the wallet

### LINKED ISSUE #3326: Show new keys without user having to refresh
## The Chore

If a user adds keys to their Vega wallet the user must refresh and reload their wallet for it to appear.

## Tasks

- [ ] Refetch list of keys when user opens Vega wallet dropdown

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #3326 

# Description ℹ️

Fetch new keys without re-connecting the wallet.

# Demo 📺

After creating a new key: 
Screenshot 2023-04-19 at 15 18 13

The console will pick it up as soon as users opens dropdown/drawer to select it.  
image

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

File: apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx [hunk 1]
```diff
@@ -162,7 +169,11 @@ export const VegaWalletConnectButton = () => {
             trigger={
               <DropdownMenuTrigger
                 data-testid="manage-vega-wallet"
-                onClick={() => setDropdownOpen((curr) => !curr)}
+                onClick={() => {
+                  const dropdownOpenState = !dropdownOpen;
+                  fetchPubKeys();
+                  setDropdownOpen(dropdownOpenState);
```
Comment (MadalinaRaicu) [inline apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx:175]:
```suggestion
                  setDropdownOpen(!dropdownOpen);
```

File: apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx [hunk 2]
```diff
@@ -162,7 +169,11 @@ export const VegaWalletConnectButton = () => {
             trigger={
               <DropdownMenuTrigger
                 data-testid="manage-vega-wallet"
-                onClick={() => setDropdownOpen((curr) => !curr)}
+                onClick={() => {
+                  const dropdownOpenState = !dropdownOpen;
```
Comment (MadalinaRaicu) [inline apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx:173]:
```suggestion
```

File: libs/wallet/src/context.ts [hunk 3]
```diff
@@ -31,6 +31,9 @@ export interface VegaWalletContextShape {
     /** Transaction payload */
     transaction: Transaction
   ) => Promise<TransactionResponse | null>;
+
+  /** Fetch public keys */
+  fetchPubKeys: () => Promise<PubKey[] | null>;
```
Comment (MadalinaRaicu) [inline libs/wallet/src/context.ts:36]:
```suggestion
  fetchPubKeys?: () => Promise<PubKey[] | null>;
```

**Review by asiaznik — APPROVED** [review]
