### PR TITLE
fix(trading): show full node URI in trading footer

### LINKED ISSUE #3923: Data node domain name truncated in Console footer
## Description

I'm connected to the `darling.network` data node and the footer just shows `network`:

image

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #3923 

# Description ℹ️

Show full node URI in the trading footer.

# Demo 📺

Before:
Screenshot 2023-05-26 at 14 43 30

After:
Screenshot 2023-05-26 at 14 44 09

### CODE REVIEW

File: apps/trading/components/footer/footer.tsx [hunk 1]
```diff
@@ -65,9 +65,8 @@ interface NodeUrlProps {
 }
 
 export const NodeUrl = ({ url }: NodeUrlProps) => {
-  // get base url from api url, api sub domain
   const urlObj = new URL(url);
-  const nodeUrl = urlObj.origin.replace(/^[^.]+\./g, '');
+  const nodeUrl = urlObj.origin;
```
Comment (edd) [inline apps/trading/components/footer/footer.tsx:69]:
```suggestion
  const nodeUrl = urlObj.hostname;
```

**thought (non-blocking)**: Non blocking, but this would give (e.g. `darling.network` rather than `https://darling.network`, or `n09.d.vega.xyz` rather `https://n09.d.vega.xyz`. Both are OK though.

**Review by edd — APPROVED** [review]
