### PR TITLE
fix(trading): fix price monitoring bounds and trigger mismatch

### LINKED ISSUE #5576: Price Monitoring details seem mixed up when there are multiple bounds
## Description

When there are multiple price monitoring bounds on a market, some of the details do not seem to line up correctly (e.g the length of auction for one and the price bounds from another will be displayed on the same box (Note in the below that the tightest bounds in the raw data are for the shortest time period, which is correct, but are for the longest in the image):

image

```json
{
  "data": {
    "market": {
      "data": {
        "timestamp": "2024-01-08T09:36:39.427104Z",
        "priceMonitoringBounds": [
          {
            "trigger": {
              "probability": 0.9999999,
              "horizonSecs": 360
            },
            "minValidPrice": "1316",
            "maxValidPrice": "1388"
          },
          {
            "trigger": {
              "probability": 0.9999999,
              "horizonSecs": 1440
            },
            "minValidPrice": "1281",
            "maxValidPrice": "1426"
          },
          {
            "trigger": {
              "probability": 0.9999999,
              "horizonSecs": 4320
            },
            "minValidPrice": "1232",
            "maxValidPrice": "1484"
          }
        ]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #5576 

# Description ℹ️

Fixing price monitoring bounds and trigger mismatch. 

# Demo 📺

Screenshot 2024-01-08 at 11 52 02

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

File: libs/markets/src/lib/components/market-info/market-info-panels.tsx [hunk 1]
```diff
@@ -698,17 +698,13 @@ export const PriceMonitoringBoundsInfoPanel = ({
...
   const quoteUnit = getQuoteName(market);
 
-  const trigger =
-    market.priceMonitoringSettings?.parameters?.triggers?.[triggerIndex];
-
   const bounds = data?.priceMonitoringBounds?.[triggerIndex];
+  const trigger = bounds?.trigger;
 
   if (!trigger) {
-    console.error(
```
Comment (MadalinaRaicu) [inline libs/markets/src/lib/components/market-info/market-info-panels.tsx:707]: very unuseful error log -  this will be undefined initially

**Review by bwallacee — APPROVED** [review]
