### PR TITLE
fix: included origin of token, moved formatters

### LINKED ISSUE #1137: TFE Disassociation - Include origin of token within select dropdown
Currently when dissassociating tokens if both vesting and wallet tokens are associated, the select dropdown doesn't identify  what the select option origin is.

There is a tooltip which takes 3 seconds to appear (which does show this info) see screenshot 
- but from a UX perspective i totally missed it - better to include within the dropdown itself - agreed with Michael

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes #1137

# Description ℹ️

Changed options description to identify what the select option origin is.

# Demo 📺

Screenshot 2022-08-24 at 20 07 47
Screenshot 2022-08-24 at 20 11 06

# Technical 👨‍🔧

Format number housekeeping included.

### CODE REVIEW

**Review by radoslaw-szpiech — APPROVED** [review]

File: apps/token/src/lib/format-number.ts [hunk 1]
```diff
@@ -1,33 +1,9 @@
...
-    .split(separator);
-  return [integers, decimalsPlaces || ''];
-};
-
-export const useNumberParts = (
-  value: BigNumber | null | undefined,
-  decimals: number
-): [integers: string, decimalPlaces: string] => {
-  return React.useMemo(() => toNumberParts(value, decimals), [decimals, value]);
+  return format(
```
Comment (MadalinaRaicu) [inline apps/token/src/lib/format-number.ts:5]: (non-blocking): is this very token dApp specific? can't we move it or use directly what we have in react-helpers lib?

Comment (MadalinaRaicu) [reply apps/token/src/lib/format-number.ts:5]: I see we have another formatNumber there. I would've renamed it and moved it in react-helpers to be reused.

**Review by MadalinaRaicu — APPROVED** [review]
