### PR TITLE
fix(#2569): market id copy update

### LINKED ISSUE #2569: Show market ID on markets table
## The Chore

Show the market Id on the markets table

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #2569

# Description ℹ️

- [x] show market ID in markets table
- [x] make it copyable
- [x] update description

# Demo 📺

Screenshot 2023-01-16 at 17 32 11

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

File: libs/market-list/src/lib/components/markets-container/market-list-table.tsx [hunk 1]
```diff
@@ -30,6 +30,7 @@ export const MarketListTable = forwardRef<
   return (
     <AgGrid
       style={{ width: '100%', height: '100%' }}
+      enableCellTextSelection={true}
```
Comment (mattrussell36) [inline libs/market-list/src/lib/components/markets-container/market-list-table.tsx:33]: suggestion (non blocking): Can we add this as a default prop to:

libs/ui-toolkit/src/components/ag-grid/ag-grid-lazy-themed.tsx
and
libs/ui-toolkit/src/components/ag-grid/ag-grid-dynamic-themed.tsx

I think you should be able to highlight and copy cells by default on all tables

**Review by mattrussell36 — APPROVED** [review]

File: libs/market-list/src/lib/components/markets-container/market-list-table.tsx (hunk 1 above)
Comment (MadalinaRaicu) [reply libs/market-list/src/lib/components/markets-container/market-list-table.tsx]: updated!
