### PR TITLE
fix: order warning messages

### LINKED ISSUE #997: Revisit deal ticket warning messages before placing orders
Revisit the warning message because persistent limit orders are accepted, including GFA, GTT, GTC as well as liquidity commitments. 
Also may be worth including the fact that as the market is suspended, any orders placed now will not trade until the auction ends.

Image

https://vegaprotocol.slack.com/archives/C8WS7M50E/p1660131156926369

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #997 & #950 & #968

# Description ℹ️

Revisit the warning message because persistent limit orders are accepted, including GFA, GTT, GTC as well as liquidity commitments.
If the market is suspended, any orders placed now will not trade until the auction ends.

# Demo 📺 & Technical 👨‍🔧
Screenshot 2022-08-15 at 17 09 49
Screenshot 2022-08-15 at 17 10 05
Screenshot 2022-08-15 at 17 10 13
Screenshot 2022-08-15 at 17 10 25
image

Screenshot 2022-08-15 at 19 01 46
Screenshot 2022-08-15 at 19 01 39

### CODE REVIEW

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 1]
```diff
@@ -88,65 +81,13 @@ export const useOrderValidation = ({
       };
     }
 
-    if (market.state !== MarketState.Active) {
-      if (market.state === MarketState.Suspended) {
-        if (market.tradingMode === MarketTradingMode.Continuous) {
```
Comment (MadalinaRaicu) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:93]: this was wrong. continuous trading (i.e. not in auction) would keep the market in the active state.

File: libs/orders/src/lib/components/order-feedback/order-feedback.tsx [hunk 2]
```diff
@@ -113,6 +74,27 @@ export const OrderFeedback = ({ transaction, order }: OrderFeedbackProps) => {
...
+const rejectionReason = (
+  order: OrderEvent_busEvents_event_Order
+): string | null => {
+  switch (order.status) {
+    case OrderStatus.Stopped:
+      return t(
+        `The network could not fill the ${order.timeInForce} order and it has been stopped`
+      );
+    case OrderStatus.Rejected:
+      return order.rejectionReason && t(formatLabel(order.rejectionReason));
```
Comment (MadalinaRaicu) [inline libs/orders/src/lib/components/order-feedback/order-feedback.tsx:96]: reason coming from the backend only when the order is Rejected. we could still add other messages that can appear when the order is Cancelled or Parked.

File: package.json [hunk 3]
```diff
@@ -6,7 +6,8 @@
     "start": "nx serve",
     "build": "nx build",
     "test": "nx test",
-    "postinstall": "husky install && yarn tsc -b tools/executors/next && yarn tsc -b tools/executors/webpack"
+    "postinstall": "husky install && yarn tsc -b tools/executors/next && yarn tsc -b tools/executors/webpack",
+    "test-all": "nx run-many --all --target=test"
```
Comment (dexturr) [inline package.json:10]: nitpick: can we make this `test:all` I prefer using colons for commands that have subtle differences

Comment (MadalinaRaicu) [inline package.json:10]:
```suggestion
    "test:all": "nx run-many --all --target=test"
```

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx [hunk 4]
```diff
@@ -88,15 +88,23 @@ export const OrderEditDialog = ({
         <form onSubmit={handleSubmit(onSubmit)} data-testid="edit-order">
           <FormGroup label={t('Entry price')} labelFor="entryPrice">
             <Input
```
Comment (notbot00) [inline libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:90]: question (non-blocking): not sure if we need to / want to add the market decimalPlaces so that the input `step` can reflect the minimum unit of change

File: libs/orders/src/lib/components/order-feedback/order-feedback.tsx [hunk 5]
```diff
@@ -113,6 +74,27 @@ export const OrderFeedback = ({ transaction, order }: OrderFeedbackProps) => {
...
+        <div>
+          <p className={labelClass}>{t(`Reason`)}</p>
+          <p data-testid="error-reason">{t(orderRejectionReason)}</p>
+        </div>
+      )}
     </div>
   );
 };
+
+const rejectionReason = (
```
Comment (notbot00) [inline libs/orders/src/lib/components/order-feedback/order-feedback.tsx:87]: nit (non-blocking): i find it a lot more readable when looking at a variable and being able to assume it's a function. usually prefixing it with a verb makes it obvious, like `getRejectionReason`. no big deal tho, pls free free to resolve this without action

File: libs/orders/src/lib/components/order-feedback/order-feedback.tsx [hunk 6]
```diff
@@ -113,6 +74,27 @@ export const OrderFeedback = ({ transaction, order }: OrderFeedbackProps) => {
...
+  order: OrderEvent_busEvents_event_Order
+): string | null => {
+  switch (order.status) {
+    case OrderStatus.Stopped:
+      return t(
+        `The network could not fill the ${order.timeInForce} order and it has been stopped`
```
Comment (candida-d) [inline libs/orders/src/lib/components/order-feedback/order-feedback.tsx:93]: suggestion (non-blocking): What about the below, which I think sounds friendlier. 

```suggestion
        `Your ${order.timeInForce} order could not be filled and it has been stopped`
```

File: libs/orders/src/lib/components/order-feedback/order-feedback.tsx (hunk 5 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/components/order-feedback/order-feedback.tsx]: updated

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx (hunk 4 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:90]: this is how it looks like after i pulled latest changes on master

Comment (notbot00) [reply libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:90]: this looks more like a side-effect of changing the input type from "text" to "number". number types need a "step" attribute in order to accept decimal values

Comment (MadalinaRaicu) [reply libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:89]: updated

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx [hunk 7]
```diff
@@ -88,15 +87,24 @@ export const OrderEditDialog = ({
...
-              {...register('entryPrice', { required: t('Required') })}
-              id="entryPrice"
               type="text"
+              step={step}
```
Comment (notbot00) [inline libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:91]: chore (blocking): so, inputs with type="text" cannot have steps, only input type="number". if you make it a text input, the step attribute becomes redundant.

File: libs/react-helpers/src/lib/format/number.ts [hunk 8]
```diff
@@ -4,7 +4,7 @@ import memoize from 'lodash/memoize';
 import { getUserLocale } from './utils';
 
 export function toDecimal(numberOfDecimals: number) {
-  return Math.pow(10, -numberOfDecimals);
```
Comment (MadalinaRaicu) [inline libs/react-helpers/src/lib/format/number.ts:7]: this never worked. because javascript is javascript 
Screenshot 2022-08-16 at 18 36 02

File: libs/orders/src/lib/components/order-feedback/order-feedback.tsx [hunk 9]
```diff
@@ -113,6 +74,27 @@ export const OrderFeedback = ({ transaction, order }: OrderFeedbackProps) => {
...
   );
 };
+
+const getRejectionReason = (
+  order: OrderEvent_busEvents_event_Order
+): string | null => {
+  switch (order.status) {
+    case OrderStatus.Stopped:
+      return t(
+        `Your ${order.timeInForce} order was not filled and it has been stopped`
```
Comment (MadalinaRaicu) [inline libs/orders/src/lib/components/order-feedback/order-feedback.tsx:93]: This will be revisited as soon as we get a `reason` behind why the order has been stopped by Vega. @campbellssource

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx [hunk 10]
```diff
@@ -37,15 +37,15 @@ export const OrderEditDialog = ({
...
-  });
+    setValue,
+  } = useForm<FormFields>();
 
   if (!order) return null;
+  const step = toDecimal(order.market?.decimalPlaces ?? 0);
+  setValue(
+    'entryPrice',
+    addDecimalsFormatNumber(order.price, order.market?.decimalPlaces ?? 0)
+  );
```
Comment (notbot00) [inline libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:48]: chore (blocking?): sorry for holding this up again, i think it would feel a lot less complicated to render this dialog from the parent with a required order object, and leave the defaultValues as it was, so you don't need to return null from the component, and don't need to forcefully reset the field value on every render.

```
{order && < OrderEditDialog  order={order} />}
```

File: libs/orders/src/lib/components/order-feedback/order-feedback.tsx [hunk 11]
```diff
@@ -18,46 +18,7 @@ export const OrderFeedback = ({ transaction, order }: OrderFeedbackProps) => {
...
-              <p className={labelClass}>{t(`Market`)}</p>
-              <p>{t(`${order.market.name}`)}</p>
-            </div>
-          )}
-        </div>
-        <div>
-          {transaction.txHash && (
-            <div>
-              <p className={labelClass}>{t('Transaction')}</p>
-              <a
```
Comment (mattrussell36) [inline libs/orders/src/lib/components/order-feedback/order-feedback.tsx:46]: question (non blocking): Are we fine not showing the vega tx hash?

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx (hunk 10 above)
Comment (mattrussell36) [reply libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:48]: Yup in React if you are setting state in render you are 100% doing something wrong.

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx [hunk 12]
```diff
@@ -88,15 +88,24 @@ export const OrderEditDialog = ({
...
+              })}
               id="entryPrice"
-              type="text"
             />
             {errors.entryPrice?.message && (
               <InputError intent="danger" className="mt-4">
                 {errors.entryPrice.message}
               </InputError>
             )}
+            {errors.entryPrice?.type === 'min' && (
```
Comment (mattrussell36) [inline libs/orders/src/lib/components/order-list/order-edit-dialog.tsx:104]: chore (blocking): You should be able to just render the message once here provided you have set up the validation using the register function. Check out the react-hook-form docs..

You should be able to do something like
```
register('entryPrice', {
  validation: {
    min: (value) => {
      if (value is valid) return true
      return 'The price cannot be negative'
    } 
  }
})
```

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 13]
```diff
@@ -186,14 +128,17 @@ export const useOrderValidation = ({
       };
     }
 
-    if (fieldErrors?.price?.type === 'required') {
+    if (
+      fieldErrors?.price?.type === 'required' &&
```
Comment (mattrussell36) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:132]: chore (blocking): You shouldn't have to conditionally change the error message by `type` if using the validate property in the `register` function of the field.

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/orders/src/lib/components/order-feedback/order-feedback.tsx (hunk 11 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/components/order-feedback/order-feedback.tsx:46]: we are showing the tx hash on line 72

Comment (MadalinaRaicu) [reply libs/orders/src/lib/components/order-feedback/order-feedback.tsx:46]: cancelled/rejected vs confirmed order were too similar - we would display the same component for both, the title would change based on the order status and if the order is rejected/stopped then we would display a reason

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx (hunk 10 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/components/order-list/order-edit-dialog.tsx]: yeah, my bad. updated.

File: libs/react-helpers/src/lib/format/number.ts [hunk 14]
```diff
@@ -4,7 +4,7 @@ import memoize from 'lodash/memoize';
...
+  return 1 / Math.pow(10, numberOfDecimals);
```
Comment (MadalinaRaicu) [inline libs/react-helpers/src/lib/format/number.ts:7]: and this works till `numberOfDecimals === 6`

File: libs/orders/src/lib/components/order-list/order-edit-dialog.tsx (hunk 12 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/components/order-list/order-edit-dialog.tsx]: updated

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx (hunk 13 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx:132]: the reason why tried to handle most the of the warning messages in 'useOrderValidation' hook is because I wanted to handle better the order in which these messages appear and to do that in one place. 
 
 i.e. here,  if I move these rules to validate, works well if the market is trading continuously but if it is in a monitoring auction then the 'You cannot set a negative price` error gets overridden by `Any orders traded now will not trade until the execution ends`
 
 
image

Comment (MadalinaRaicu) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx:132]: I can handle this only in register, if I add the market trading mode as a field in deal ticket limit amount where we register the form and move more rules over there, but is it better?

Comment (mattrussell36) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx:132]: No I think this is fine. Its out side the component itself so I think here its better to use the fieldErrors object.

**Review by mattrussell36 — APPROVED** [review]

**Comment by AndyWhiteVega** [comment]
Tested each = Looks good
