### PR TITLE
fix(trading): order tx toasts title and intent should be set by status

### LINKED ISSUE #3383: Fix order rejected titles on toast

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #3383 

# Description ℹ️

Transaction toasts - the title should be set based on order status.

# Demo 📺

Fixing this:
image

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

File: apps/trading/lib/hooks/use-vega-transaction-toasts.tsx [hunk 1]
```diff
@@ -39,7 +39,11 @@ import { t } from '@vegaprotocol/i18n';
 import { useAssetsDataProvider } from '@vegaprotocol/assets';
 import { useEthWithdrawApprovalsStore } from '@vegaprotocol/web3';
 import { DApp, EXPLORER_TX, useLinks } from '@vegaprotocol/environment';
-import { getRejectionReason, useOrderByIdQuery } from '@vegaprotocol/orders';
+import {
+  getOrderTitle as getOrderTitle,
```
Comment (MadalinaRaicu) [inline apps/trading/lib/hooks/use-vega-transaction-toasts.tsx:43]:
```suggestion
  getOrderTitle,
```

File: libs/orders/src/lib/order-hooks/use-order-submit.tsx [hunk 2]
```diff
@@ -13,7 +13,7 @@ import { Icon, Intent } from '@vegaprotocol/ui-toolkit';
 import { t } from '@vegaprotocol/i18n';
 import type { OrderSubmissionBody } from '@vegaprotocol/wallet';
 
-export const getOrderDialogTitle = (
+export const getOrderTitle = (
```
Comment (mattrussell36) [inline libs/orders/src/lib/order-hooks/use-order-submit.tsx:16]: chore (blocking): This file was a dead file. Can we 

a) move these helper functions to libs/orders/src/lib/utils.ts
b) rename to getOrderToastTitle etc etc
c) delete this file and corresponding test file

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

**Review by mattrussell36 — APPROVED** [review]
