### PR TITLE
fix(explorer): improve AMM submit and amend views

### LINKED ISSUE #6627: Basic support for AMM txs
## Tasks

- [x] Show correct labels in TX list
  - [x] Cancel AMM
  - [x] Amend AMM
  - [x] Submit AMM
- [ ] Show TX Details
  - [x] Cancel AMM
    - [x] Method
    - [x] `MarketLink` for Market ID
  - [ ] Submit AMM
    - [ ] commitmentAmount
    - [x] `MarketLink` for Market ID
    - [ ] proposedFee
    - [ ] slippageTolerance
    - [ ] concentratedLiquidityParameters
      - [ ] base
      - [ ] leverageAtLowerBound
      - [ ] leverageAtUpperBound
      - [ ] lowerBound
      - [ ] upperBound
  - [ ] Amend AMM (as above)

### PR DESCRIPTION
**Pull request by edd**
# Related issues 🔗

Closes #6627

# Description ℹ️

Fixes the feedback on the initial AMM tx views for submit and amend:
- Update `proposedFee` to display as percentage
- Update `slippageTolerage` to display as percentage
- Update `commitmentAmount` to be displayed in the correct asset decimals instead of market decimals
- Update `<SizeInMarket />` component to allow labels to be displayed and asset decimals to be used

# Demo 📺

Screenshot 2024-09-09 at 14 28 17

### CODE REVIEW

File: apps/explorer/src/app/components/blocks/blocks-refetch.tsx [hunk 1]
```diff
@@ -11,7 +11,12 @@ export const BlocksRefetch = ({ refetch }: BlocksRefetchProps) => {
   };
 
   return (
-    <Button onClick={refresh} data-testid="refresh" size="xs">
+    <Button
+      onClick={refresh}
+      data-testid="refresh"
+      size="xs"
+      className="dark:text-white"
```
Comment (mattrussell36) [inline apps/explorer/src/app/components/blocks/blocks-refetch.tsx:18]: You probably dont need (or at least shouldn't need this class)

**Review by mattrussell36 — COMMENTED** [review]
The use of dark:text-white is indicating that something is possibly wrong in the the stylesheet

File: apps/explorer/src/app/components/blocks/blocks-refetch.tsx (hunk 1 above)
Comment (edd) [reply apps/explorer/src/app/components/blocks/blocks-refetch.tsx:18]: These were added to fix bits that were broken by a previous conversion. If you're really against me adding them, I will remove them from this PR and do it separately.

Comment (edd) [reply apps/explorer/src/app/components/blocks/blocks-refetch.tsx:18]: Agreed in person to do this as a follow up

**Review by mattrussell36 — APPROVED** [review]
