### PR TITLE
fix(trading): fees

### LINKED ISSUE #6967: Fix NaaN issue on referral & volume program table on referral page and fees page
## Summary

The referral program and volume program can now have different discounts applied to infra / maker / liquidity components for ... reasons. As a result all the tables are broken since the APIs have changed shape.

Rather than expose all this compleity to users, we propose to work out the "overall" discount factors and reward factors and show those in the same tables as we have today.

### Discounts

With
`Total undiscounted fee = makerFee + infraFee + MAX(liquidityFee) + buybackFee + treasuryFee`

`Total discounted fee = makerFee * (1 - makerDiscount) + infraFee * (1- infraDiscount) + MAX(liquidityFee) * (1- liquidityDiscount) + buybackFee + treasuryFee`

Then
`Referral Discount = (undiscounted - discounted) / undiscounted`

### Rewards

With
`Reward = makerFee * makerFactor + infraFee * infraFactor + MAX(liquidityFee) * liquidityFactor`

`Total fee = makerFee + infraFee + MAX(liquidityFee) + buybackFee + treasuryFee`

Then
`Overall reward factor = reward / total fee`

NB. 
Also adjust the tooltip 
- From "The proportion of the referee's taker fees to be rewarded to the referrer"
- To "The maximum proportion of the referee's taker fees to be rewarded to the referrer without accounting for any referee discounts"

### Discounts

With 

`Total undiscounted fee = makerFee + infraFee + MAX(liquidityFee) + buybackFee + treasuryFee`

`Total discounted fee = makerFee * (1 - makerDiscount) + infraFee * (1- infraDiscount) + MAX(liquidityFee) * (1- liquidityDiscount) + buybackFee + treasuryFee`

Then

`Volume Discount = (undiscounted - discounted) / undiscounted`

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes #6967 

# Description ℹ️

* adds support to the new fee factors
* displays factors in referral pages and fees pages
* displays 'at least XXX' in apply code step

# Demo 📺

Screenshot 2024-09-25 at 16 19 20
Screenshot 2024-09-25 at 16 19 35
Screenshot 2024-09-25 at 16 19 40
Screenshot 2024-09-25 at 16 19 49
Screenshot 2024-09-25 at 16 19 56

### CODE REVIEW

File: apps/trading/lib/hooks/use-current-programs.ts [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+    buybackFee,
+    infrastructureFee,
+    liquidityFee: min(liquidityFees) || 0,
+    makerFee,
+    treasuryFee,
+  };
+}
+
+function calcRewardFactor(fees: Fees, factors: Factors) {
+  const MF = BigNumber(fees.makerFee).times(factors.makerFactor);
```
Comment (mattrussell36) [inline apps/trading/lib/hooks/use-current-programs.ts:224]: Coming to this code fresh, its not immediately clear what these variables are, and all caps should ideally be reserved for true constants. Can we just name these `makerFee` etc

File: apps/trading/lib/hooks/use-current-programs.ts [hunk 2]
```diff
@@ -0,0 +1,289 @@
...
+
+  return discountFactor;
+}
+
+export function areFactorsEqual(a: Factors, b: Factors) {
+  const infra = a.infrastructureFactor === b.infrastructureFactor;
+  const liqui = a.liquidityFactor === b.liquidityFactor;
+  const maker = a.makerFactor === b.makerFactor;
+  return infra && liqui && maker;
+  // return isEqual(a, b)
```
Comment (mattrussell36) [inline apps/trading/lib/hooks/use-current-programs.ts:280]: Do we need this?

File: apps/trading/lib/hooks/use-current-programs.ts [hunk 3]
```diff
@@ -0,0 +1,289 @@
...
+
+  return {
+    referralProgram,
+    volumeDiscountProgram,
+    loading,
+    error,
+  };
+};
+
+function prepareReferralBenefitTiers(
```
Comment (mattrussell36) [inline apps/trading/lib/hooks/use-current-programs.ts:129]: Lots of data manipulation and calculation in this file. It would benefit from a unit test

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

**Review by mattrussell36 — APPROVED** [review]
