### PR TITLE
fix: 1842 set expiry to date time format

### LINKED ISSUE #1842: Show expiry time in trade page header
We currently only show the date but not the time. We should show the time as well.

Current:
Screenshot 2022-10-24 at 15 58 20

## Tasks

- [ ] Adjust date format to include time

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #1842 

# Description ℹ️

set expiry to date time format

# Demo 📺 
Screenshot 2022-10-26 at 16 12 30

### CODE REVIEW

File: libs/market-info/src/components/market-expires/market-expires.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
-import type { SingleMarketFieldsFragment } from '@vegaprotocol/market-list';
-import { getDateFormat, t } from '@vegaprotocol/react-helpers';
+import { getDateTimeFormat, t } from '@vegaprotocol/react-helpers';
 import { format, isValid, parseISO } from 'date-fns';
 
+import type { SingleMarketFieldsFragment } from '@vegaprotocol/market-list';
 export const EXPIRE_DATE_FORMAT = 'MMM dd';
```
Comment (mattrussell36) [inline libs/market-info/src/components/market-expires/market-expires.tsx:5]: question (blocking): do we not need to update this format string? Looks like there is a mix of using date-fns for formatting as well the Intl object. Can we tidy this up to use the later?

Comment (MadalinaRaicu) [reply libs/market-info/src/components/market-expires/market-expires.tsx:5]: I kept this format because it was used in console-lite. I don't know the reqs/designs on that one and I didn't want this PR to affect anything else except the console.

**Review by dexturr — APPROVED** [review]
