### PR TITLE
fix(trading): missing volume discount program issue, inverted tiers

### LINKED ISSUE #5370: Invert the tiers for volume and referral benefit
## The Chore

Currently they look like this 

image

Flip this so that tier 1 is the LOWEST benefits for both lists. 

## Tasks

- [ ] Do this on the fees page
- [ ] Do this on the referrals page

### LINKED ISSUE #5376: Fees page in mainnet isnt showing the volume discount
## The Chore

What we need to achieve and who for

## Tasks

- [ ]
- [ ]

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes #5376 
Closes #5370

# Description ℹ️

* fixes missing volume discount program 
* inverts tier numbers, lowest is 1 (also in governance proposal views)

# Demo 📺

image
image

# Technical 👨‍🔧

I've added `errorPolicy` to the program queries because for some reason it panics that couldn't find the referral program 😱

### CODE REVIEW

**Review by MadalinaRaicu — APPROVED** [review]

**Review by bglownia — APPROVED** [review]

**Review by bwallacee — APPROVED** [review]

File: apps/governance/src/routes/proposals/components/proposal-referral-program-details/proposal-referral-program-details.tsx [hunk 1]
```diff
@@ -114,7 +114,7 @@ export const ProposalReferralProgramDetails = ({
                 .map((benefitTier, index) => (
                   <div className="mb-4" key={index}>
                     <h4 className="font-semibold uppercase">
-                      Tier {index + 1}
+                      Tier {benefitTiers.length - index}
```
Comment (asiaznik) [inline apps/governance/src/routes/proposals/components/proposal-referral-program-details/proposal-referral-program-details.tsx:117]: The tiers here are sorted in ascending order, so the initial way of numbering was correct.
```suggestion
                      Tier {index + 1}
```

File: apps/governance/src/routes/proposals/components/proposal-volume-discount-program-details/proposal-volume-discount-program-details.tsx [hunk 2]
```diff
@@ -87,7 +87,7 @@ export const ProposalVolumeDiscountProgramDetails = ({
                 .map((benefitTier, index) => (
                   <div className="mb-4" key={index}>
                     <h4 className="font-semibold uppercase">
-                      Tier {index + 1}
+                      Tier {benefitTiers.length - index}
```
Comment (asiaznik) [inline apps/governance/src/routes/proposals/components/proposal-volume-discount-program-details/proposal-volume-discount-program-details.tsx:90]: The tiers here are sorted in ascending order, so the initial way of numbering was correct.
```suggestion
                      Tier {index + 1}
```
