### PR TITLE
Fix/602 fix deal ticket component to be reused by both simple trading app and console v2

### LINKED ISSUE #602: Fix deal ticket component to be reused by both simple trading app and console v2

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #602 

# Description ℹ️

A bug that has been introduced in a bad merge conflict attempt to resolve deal ticket container updates. 

# Demo 📺

Fixes the issue below: 

Screenshot 2022-06-21 at 12 32 59

Gif/video/images of new/corrected functionality if applicable

# Technical 👨‍🔧

Deal ticket container gets resued in both console v2 and simple trading app.

### CODE REVIEW

**Review by elmar-vega — APPROVED** [review]

File: libs/deal-ticket/src/components/info-market.tsx [hunk 1]
```diff
@@ -9,17 +9,45 @@ import {
...
 import pick from 'lodash/pick';
 import omit from 'lodash/omit';
-import type { DealTicketQuery_market } from './__generated__/DealTicketQuery';
+import type {
+  DealTicketQuery,
+  DealTicketQuery_market,
+} from './__generated__/DealTicketQuery';
 import BigNumber from 'bignumber.js';
+import { useQuery } from '@apollo/client';
+import { DEAL_TICKET_QUERY } from './deal-ticket-container';
```
Comment (mattrussell36) [inline libs/deal-ticket/src/components/info-market.tsx:24]: chore (blocking): Lets not share the query. Instead can we update the deal ticket query to only contain what it needs and add a new market info query for everything it needs.

**Review by mattrussell36 — CHANGES_REQUESTED** [review]
Looks good though I think we shouldn't share the query across tabs. Lets separate them

**Review by sam-keen — APPROVED** [review]

File: libs/deal-ticket/src/components/info-market.tsx [hunk 2]
```diff
@@ -8,17 +8,129 @@ import {
...
-import type { DealTicketQuery_market } from './__generated__/DealTicketQuery';
+import type {
+  MarketInfoQuery,
+  MarketInfoQuery_market,
+} from './__generated__/MarketInfoQuery';
 import BigNumber from 'bignumber.js';
+import { gql, useQuery } from '@apollo/client';
+
+const MARKET_INFO_QUERY = gql`
+  query MarketInfoQuery($marketId: ID!) {
```
Comment (mattrussell36) [inline libs/deal-ticket/src/components/info-market.tsx:26]: chore (blocking): Can we add a generateMarketInfoQuery mock, and add it to our tests. Otherwise we'll get flakey tests

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/deal-ticket/src/components/info-market.tsx (hunk 2 above)
Comment (MadalinaRaicu) [reply libs/deal-ticket/src/components/info-market.tsx:26]: added.

**Review by mattrussell36 — APPROVED** [review]
