### PR TITLE
feat(governance,accounts): vesting and vested accound in wallet card, fix transfer form to account

### LINKED ISSUE #5167: Add rewards vesting accounts to the Governance app
## The Chore

The new vesting mechanics introduce some issues for governance. 

Mostly we are trying to steer ppl towards Console for everything rewards related but some users may only ever stake and not use console and therefore need some options in governance app. 

## Tasks

- [x] Ensure the connected wallet view shows the breakdown of 
  - [x] VESTING account 
  - [x] VESTED accounts
- [x] Add a button by vested account to send people to the Console trasnfer page where they can redeem them

### LINKED ISSUE #5201: New transfer page with vested account stuff showing incorrect balances
## The Chore

image

See key: b62eafc46e6fadc6e45ae51de8bda199f0702131e5b23665f3411223c598acc2
On fairground 

For now can we go with option 1 ..... fix pulling the balance in properly .... that way we can do this without Matt and then we can talk revised UX on a less urgent timeframe.   

## Tasks

- [x ] Decide on option 
- [ ] FIx it

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes #5167 
Closes #5201 

# Description ℹ️

* adds "Vesting" and "Vested" accounts to the wallet card
* sums the balances from general and vested accounts in transfer form
* adds "Redeem" button that navigates to the Console's transfer form

# Demo 📺

image

# Technical 👨‍🔧

N/A

### CODE REVIEW

**Review by MadalinaRaicu — APPROVED** [review]

File: libs/accounts/src/lib/transfer-form.tsx [hunk 1]
```diff
@@ -72,8 +72,26 @@ export const TransferForm = ({
 
   const assets = sortBy(
     accounts
-      .filter((a) => a.type === AccountType.ACCOUNT_TYPE_GENERAL)
+      .filter(
+        (a) =>
+          a.type === AccountType.ACCOUNT_TYPE_GENERAL ||
+          a.type === AccountType.ACCOUNT_TYPE_VESTED_REWARDS
+      )
+      .reduce((merged, account) => {
```
Comment (mattrussell36) [inline libs/accounts/src/lib/transfer-form.tsx:80]: This doesn't fix the issue. I still get the same general balance. Taking a look at this now...

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: libs/accounts/src/lib/transfer-form.tsx (hunk 1 above)
Comment (mattrussell36) [reply libs/accounts/src/lib/transfer-form.tsx:80]: Just to clarify, this does fix _a_ issue where the balance in the asset dropdown was only the general account. But not the one where the balance in the to account dropdown is incorrect

**Review by mattrussell36 — APPROVED** [review]
