### PR TITLE
feat: [console-lite] - fast fix small css on market selector

### LINKED ISSUE #1289: [console-lite] - fix market selector view
- [ ] change some small css for fix discrepancies after basic design update for market selector

### PR DESCRIPTION
**Pull request by macqbat**
# Related issues 🔗

Closes #1289

# Description ℹ️

Adjust some css for better looking after design update

### CODE REVIEW

File: libs/deal-ticket/src/components/deal-ticket/market-selector.tsx [hunk 1]
```diff
@@ -196,7 +196,7 @@ export const MarketSelector = ({ market, setMarket, ItemRenderer }: Props) => {
       <div className="relative flex flex-col">
         <div className="relative w-full min-h-[30px]">
           <Input
-            className="h-[30px] w-[calc(100%-20px)] border-none"
+            className="h-[30px] w-[calc(100%-20px)] border-none outline-none"
```
Comment (asiaznik) [inline libs/deal-ticket/src/components/deal-ticket/market-selector.tsx:199]: question (non-blocking): how anyone will know that this input is in focus?

Comment (macqbat) [reply libs/deal-ticket/src/components/deal-ticket/market-selector.tsx:199]: sure, cursor will be visible inside an input

**Review by asiaznik — APPROVED** [review]

File: libs/deal-ticket/src/components/deal-ticket/market-selector.tsx (hunk 1 above)
Comment (macqbat) [reply libs/deal-ticket/src/components/deal-ticket/market-selector.tsx:199]: moreover we've got there also an arrow button which facilitates a11y:
Screenshot 2022-09-08 at 15 44 26

**Review by notbot00 — APPROVED** [review]
