### PR TITLE
fix: asset dropdown list

### LINKED ISSUE #2556: Ensure asset dropdown list for account history is up to date (or show all)
## The Chore

The asset dropdown list in the account history window does not stay up to date after a deposit.

## Tasks

Either:
- [ ] Show all assets
or
- [ ] Use the aggregatedAccountsDataProvider to filter the asset list

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #2556

# Description ℹ️

Asset dropdown shows the full list of assets with history. 

# Demo 📺
After:
image

Before: 
image

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

**Review by sam-keen — APPROVED** [review]

File: apps/trading/client-pages/portfolio/account-history-container.tsx [hunk 1]
```diff
@@ -95,17 +96,15 @@ const AccountHistoryManager = ({
     [pubKey]
   );
 
-  const assetsWithBalanceHistory = useAccountsWithBalanceQuery({
+  const { data: assetsWithBalanceHistory } = useDataProvider({
```
Comment (mattrussell36) [inline apps/trading/client-pages/portfolio/account-history-container.tsx:99]: suggestion (non blocking): This variable could use renaming now its inaccurate. `accounts` or `accountsData`

**Review by mattrussell36 — APPROVED** [review]
