### PR TITLE
fix(trading): condense deal ticket & market info price range snags

### LINKED ISSUE #2964: Condense spacing of deal ticket
## The Chore

Update deal ticket spacing to follow latest more condensed design

## Tasks

- [ ] Dev
- [ ] Design review

## Additional details / background info

Extracted from original ticket here:

https://github.com/vegaprotocol/frontend-monorepo/issues/2037

206219152-a4f434fe-1f18-4ebf-929f-b19121660de5

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #2964  #2955 

# Description ℹ️ & Technical 👨‍🔧

- [x] condense deal ticket 
- [x] market info liquidity and price range bounds/triggers snags
- [x] added a missing unit test in number.tsx test for toDecimal

# Demo 📺

Screenshot 2023-02-27 at 12 42 53

Screenshot 2023-02-27 at 12 44 00

Screenshot 2023-02-27 at 12 43 07

### CODE REVIEW

File: libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ export const DealTicketMarketAmount = ({
     : undefined;
 
   return (
-    <div className="mb-6">
+    <div className="mb-4">
       <div className="flex items-end gap-4 mb-2">
         <div className="flex-1 text-sm">Size</div>
```
Comment (macqbat) [inline libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx:34]: (non-blocking): maybe, by the way, will be useful to use translation helper here?

File: libs/market-info/src/components/market-info/info-market.tsx [hunk 2]
```diff
@@ -309,27 +309,41 @@ export const Info = ({ market, onSelect }: InfoProps) => {
...
-      })
+      (trigger, i) => {
+        const bounds = market.data?.priceMonitoringBounds?.[i];
+        return {
+          title: t(`Price monitoring bounds ${i + 1}`),
+          content: (
+            <div className="text-xs">
+              <div className="grid grid-cols-2 text-xs mb-4">
+                <p className="col-span-1">
+                  {t('%s% probability of trading', [
```
Comment (macqbat) [inline libs/market-info/src/components/market-info/info-market.tsx:320]: hm, wildcard for a single word substitute is %s. Here we have two words. Not sure it will be work as expected

**Review by macqbat — APPROVED** [review]

File: libs/market-info/src/components/market-info/info-market.tsx (hunk 2 above)
Comment (MadalinaRaicu) [reply libs/market-info/src/components/market-info/info-market.tsx:320]: thanks! updated

File: libs/deal-ticket/src/components/deal-ticket/deal-ticket-limit-amount.tsx [hunk 3]
```diff
@@ -38,7 +38,7 @@ export const DealTicketLimitAmount = ({
   };
 
   return (
-    <div className="mb-6">
+    <div className="mb-4">
```
Comment (mattrussell36) [inline libs/deal-ticket/src/components/deal-ticket/deal-ticket-limit-amount.tsx:41]: chore: lest make all spacing mb-4

**Review by mattrussell36 — APPROVED** [review]
