### PR TITLE
fix(explorer,proposals): handle batch proposals in proposals table

### LINKED ISSUE #6555: proposalsDataProvider uses deprecated graphql field
## Description

https://github.com/vegaprotocol/frontend-monorepo/blob/develop/libs/proposals/src/lib/proposals-data-provider/Proposals.graphql#L451-L454

This query should use `proposalNode` instead of `node`. Not doing so leads to the Proposals list on Explorer not showing batch proposals. 

The missing proposals:
Screenshot 2024-06-14 at 11 48 03

## Steps to Reproduce

1. Go to https://explorer.vega.xyz/governance
2. Note the lack of batch proposals
3. Check the network response

```[tasklist]
### Tasks
- [x] Update proposalsDataProvider to use proposalNode for ProposalListQuery
```

### PR DESCRIPTION
**Pull request by edd**
- **chore(types,proposals,explorer): regenerate types switching proposals node to proposalnode**
- **chore(explorer,proposals): populate all important columns with batch info**
- **feat(explorer,proposals): select subproposals for the json dialog**

# Related issues 🔗

Closes #6555

# Description ℹ️

The Proposals lib (used only in Explorer) was using a deprecated GraphQL type to select proposals. This resulted in Batch Proposals not appearing in the proposal list. This PR updates the graphQL query & handles batch proposals for the table.

Note that the _Enacted_ column has been removed. Each proposals in a sub proposal has an individual enactment time, which makes this column not applicable. I made the decision to remove the column, because this component the enactment time is available in the JSON dialog, and most recent proposals are in batches which made this column useless. The `Status` column does the job of indicating if the proposal has hit its enactment period.

# Demo 📺
## Batches now appear in the list
Screenshot 2024-06-28 at 16 18 39

## JSON view is populated with the subproposals
Screenshot 2024-06-28 at 16 19 43

### CODE REVIEW

File: apps/explorer/src/app/components/proposals/proposals-table.tsx [hunk 1]
```diff
@@ -81,27 +87,16 @@ export const ProposalsTable = ({ data }: ProposalsTableProps) => {
...
-        maxWidth: 150,
-        hide: window.innerWidth <= BREAKPOINT_MD,
-        headerName: t('Enactment date'),
-        field: 'terms.enactmentDatetime',
         valueFormatter: ({
           value,
         }: VegaValueFormatterParams<
           ProposalListFieldsFragment,
-          'terms.enactmentDatetime'
+          'terms.closingDatetime'
```
Comment (edd) [inline apps/explorer/src/app/components/proposals/proposals-table.tsx:99]: Note: this diff is a little misleading, I definitely didn't just change the enactment column to show closing
