### PR TITLE
fix: filter rejected markets, order when suspended, remove market state from header, show continuous trading

### LINKED ISSUE #603: Filter out rejected market proposals form the list of markets
Image

This markets list contains markets that have been proposed but will never become markets. They should not appear here.
Proposed markets that have a chance of becoming real should go here (because users may wish to provide liquidity.

To determine if a market has a chance of becoming real we could look at the proposal status. In this case the cabbages market has a proposal state of rejected, so should not be returned in the markets list

```GraphQL
newMarketProposals{
    state
    id
    terms{
      change{
        ...on NewMarket{
          instrument{
            name
          }
        }
      }
    }
  }
...
markets{
  id
  state
  name
}
```
```GraphQL
{
  "state": "Rejected",
  "id": "a9ef0c09d88f7873eb0f86538dfaa0e45a4107f311b0b885b67d8bd4da49e289",
  "terms": {
    "change": {
      "instrument": {
        "name": "Cabbage"
      }
    }
  }
}
...
{
  "id": "a9ef0c09d88f7873eb0f86538dfaa0e45a4107f311b0b885b67d8bd4da49e289",
  "state": "Proposed",
  "name": "Cabbage"
},
```

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #603 #656 #609

# Description ℹ️ 

- [x] filter rejected markets (data node returns also already rejected markets)
- [x] order when suspended
- [x] remove market state from header
- [x] show continuous trading
- [x] enable trading when market suspended

# Demo 📺

image

image

# Technical 👨‍🔧
Details of technical implementation that reviewers may need to be aware of, if applicable.

- [x] change use order validation hook to display correct warnings and enable trading

### CODE REVIEW

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 1]
```diff
@@ -28,33 +28,112 @@ export const useOrderValidation = ({
...
 
     if (keypair.tainted) {
-      return t('Selected public key has been tainted');
+      return {
+        isDisabled: true,
+        message: t('Selected public key has been tainted'),
+      };
+    }
+
+    if (
```
Comment (MadalinaRaicu) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:43]: @campbellssource @PeteWilliams @jtsang586 

it would be great if I can have your review on this file.

File: apps/trading/pages/markets/trade-grid.tsx [hunk 2]
```diff
@@ -87,20 +89,18 @@ export const TradeMarketHeader = ({
...
             <span className={itemClassName}>Trading mode</span>
             <span data-testid="trading-mode" className={itemValueClassName}>
-              {market.tradingMode}
-            </span>
-          </div>
-          <div className={headerItemClassName}>
-            <span className={itemClassName}>State</span>
-            <span data-testid="market-state" className={itemValueClassName}>
-              {market.state}
+              {startCase(
```
Comment (notbot00) [inline apps/trading/pages/markets/trade-grid.tsx:99]: chore (potentially-blocking): i think ideally we want to have a translation for this

File: libs/ui-toolkit/src/components/dialog/dialog.tsx [hunk 3]
```diff
@@ -26,7 +26,7 @@ export function Dialog({
 }: DialogProps) {
   const contentClasses = classNames(
     // Positions the modal in the center of screen
-    'z-20 fixed w-full md:w-[520px] lg:w-[1000px] px-28 py-24 top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]',
```
Comment (notbot00) [inline libs/ui-toolkit/src/components/dialog/dialog.tsx:29]: question (blocking): i believe this was a requirement agreed by @sam-keen and @PeteWilliams that the modal sizes should be uniform and that particular size to accommodate the node switcher, because it looked pretty cramped under ~850px.
I've ended up changing this to 960px >[here](https://github.com/vegaprotocol/frontend-monorepo/pull/741/files#diff-1a450fe1bce39104bcd5b2c6b764f71945dbbd98f3f5b4bb7aae39138bda92acR29)< to prevent overflows, as it turns out our lg breakpoint os 960px.

File: apps/trading/pages/markets/trade-grid.tsx [hunk 4]
```diff
@@ -87,20 +89,18 @@ export const TradeMarketHeader = ({
             <span className={itemClassName}>Volume</span>
             <span data-testid="trading-volume" className={itemValueClassName}>
               {market.data && market.data.indicativeVolume !== '0'
-                ? market.data.indicativeVolume
+                ? formatNumber(market.data.indicativeVolume)
```
Comment (mattrussell36) [inline apps/trading/pages/markets/trade-grid.tsx]: chore (blocking): Probably want to format with market.positionDecimal places here.

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx (hunk 1 above)
Comment (mattrussell36) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx:43]: Also @candida-d

File: libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx [hunk 5]
```diff
@@ -90,107 +90,146 @@ function setup(
...
+describe(`useOrderValidation`, () => {
+  it('Returns empty string when given valid data', () => {
+    const { result } = setup();
+    expect(result.current).toStrictEqual({ isDisabled: false, message: `` });
+  });
 
-it('Returns an error message when the keypair is tainted', async () => {
-  const { result } = setup(defaultOrder, {
-    keypair: { ...defaultWalletContext.keypair, tainted: true },
+  it('Returns an error message when no keypair found', async () => {
```
Comment (mattrussell36) [inline libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx:99]: question (blocking): Do all these tests need to be async. Nothing async is happening in the hook or the tests

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 6]
```diff
@@ -28,33 +28,112 @@ export const useOrderValidation = ({
...
+      [
+        MarketState.Settled,
+        MarketState.Rejected,
+        MarketState.TradingTerminated,
+      ].includes(market.state)
+    ) {
+      return {
+        isDisabled: true,
+        message: t(
+          `This market is ${market.state.toLowerCase()} and no longer accepting orders`
```
Comment (mattrussell36) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:53]: chore (non-blocking): we might want to add a map of market states to translations. Right now this could read "This market is tradingterminated and no longer accepting orders".

Perhaps a map like
```
const marketTranslations: { [S in MarketState]: string } = {
  [MarketState.TradingTerminated]: t('terminated'),
  [MarketState.Rejected]: t('rejected')
  ... // and so on
}
...
message: t(`This market is now ${marketTranslations[market.state]}' and is no longer accepting orders`)
```

Comment (mattrussell36) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx:53]: Worth checking the other resulting messages too.

**Review by mattrussell36 — CHANGES_REQUESTED** [review]

File: apps/trading/pages/markets/trade-grid.tsx (hunk 4 above)
Comment (MadalinaRaicu) [reply apps/trading/pages/markets/trade-grid.tsx]: just updated

File: libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx (hunk 5 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx]: I did not change this, they were async before but they don't need to be. Updated.

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx (hunk 6 above)
Comment (MadalinaRaicu) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx]: updated

**Review by notbot00 — APPROVED** [review]

File: apps/trading/pages/markets/__generated__/Market.ts [hunk 7]
```diff
@@ -144,6 +144,12 @@ export interface Market_market {
    * GBX (pence)        1              4       GBP   0.000001 (  0.0001p)
    */
   decimalPlaces: number;
+  /**
+   * positionDecimalPlaces indicated the number of decimal places that an integer must be shifted in order to get a correct size (uint64).
```
Comment (candida-d) [inline apps/trading/pages/markets/__generated__/Market.ts:148]:
```suggestion
   * positionDecimalPlaces indicate the number of decimal places that an integer must be shifted in order to get a correct size (uint64).
```

File: libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx [hunk 8]
```diff
@@ -90,107 +91,148 @@ function setup(
...
+    ${MarketState.Settled}
+    ${MarketState.Rejected}
+    ${MarketState.TradingTerminated}
+  `(
+    'Returns an error message for market state when no longer accepting orders',
+    ({ state }) => {
+      const { result } = setup({ market: { ...defaultOrder.market, state } });
+      expect(result.current).toStrictEqual({
+        isDisabled: true,
+        message: `This market is ${marketTranslations(
```
Comment (candida-d) [inline libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx:123]: If I'm reading this correctly, then I believe it should say "This market is (state) and not accepting orders", because, for example, a market that is pending will not have been able to take orders yet, ever.

File: libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx [hunk 9]
```diff
@@ -90,107 +91,148 @@ function setup(
...
-    market: { ...market, positionDecimalPlaces: 0 },
-    fieldErrors: { size: { type: 'validate', message: ERROR_SIZE_DECIMAL } },
   });
-  expect(result.current).toEqual(ERROR.FIELD_PRICE_STEP_NULL);
-});
 
-it('Returns an error message when the order size has more decimals then allowed', async () => {
-  const { result } = setup({
-    fieldErrors: { size: { type: 'validate', message: ERROR_SIZE_DECIMAL } },
+  it('Returns an error message when the order size has more decimals then allowed', () => {
```
Comment (candida-d) [inline libs/orders/src/lib/order-hooks/use-order-validation.spec.tsx:229]:
```suggestion
  it('Returns an error message when the order size has more decimals than allowed', () => {
```

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 10]
```diff
@@ -28,33 +37,120 @@ export const useOrderValidation = ({
...
+      [
+        MarketState.Settled,
+        MarketState.Rejected,
+        MarketState.TradingTerminated,
+      ].includes(market.state)
+    ) {
+      return {
+        isDisabled: true,
+        message: t(
+          `This market is ${marketTranslations(
```
Comment (candida-d) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:62]: I might have left this comment in the wrong place (sorry if I did as now it's in 2 places) but ... 

If I'm reading this correctly, then I believe it should say "This market is (state) and not accepting orders", because, for example, a market that is proposed will not have been able to take orders yet, ever.

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 11]
```diff
@@ -28,33 +37,120 @@ export const useOrderValidation = ({
...
         market.state === MarketState.Proposed ||
         market.state === MarketState.Pending
       ) {
-        return t('Market is not active yet');
+        return {
+          isDisabled: false,
+          message: t(
+            `This market is ${marketTranslations(
+              market.state
+            )} and only accepting liquidity orders`
```
Comment (candida-d) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:135]:
```suggestion
            )} and only accepting liquidity commitment orders`
```

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 12]
```diff
@@ -28,33 +37,120 @@ export const useOrderValidation = ({
...
+            };
+          }
+        }
+
+        return {
+          isDisabled: false,
+          message: t(
+            `This market is ${marketTranslations(
+              market.state
+            )} and only accepting liquidity orders`
```
Comment (candida-d) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:121]:
```suggestion
            )} and only accepting liquidity commitment orders`
```

**Review by candida-d — COMMENTED** [review]
I added in some suggested changes, and some comments - all on the wording. :)

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 13]
```diff
@@ -64,41 +160,62 @@ export const useOrderValidation = ({
...
 
     if (
       fieldErrors?.size?.type === 'validate' &&
       fieldErrors?.size?.message === ERROR_SIZE_DECIMAL
     ) {
       if (market.positionDecimalPlaces === 0) {
-        return t('No decimal amounts allowed for this order');
+        return {
+          isDisabled: true,
+          message: t('No decimal amounts allowed for this order'),
```
[the remark this answers is not in the document]
Comment (MadalinaRaicu) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx]: updated to the suggested wording

**Comment by MadalinaRaicu** [comment]
> I added in some suggested changes, and some comments - all on the wording. :)

thanks for the review and for using the `suggest a change` feature!  made updating really easy

**Review by dexturr — APPROVED** [review]

**Review by mattrussell36 — APPROVED** [review]

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (PeteWilliams) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx]: @candida-d I think 'fractional' might be a bit confusing.
Would something like 'Order sizes must be whole numbers for this market' make more sense?
Think it's usually best to tell users what they need to do rather than what they can't do where possible, and might avoid confusing terms in this instance.

**Comment by PeteWilliams** [comment]
Looking at @campbellssource's requirements on https://github.com/vegaprotocol/frontend-monorepo/issues/656 I think there's a couple things we're missing:

> if market.tradingmode = monitoring auction then also show market.data.trigger to show if it is a liquidity or price monitoring auction

That could look like this
image

Can we also change the capitalised cases to sentence case (ie, 'Monitoring Auction' becomes 'Monitoring auction')?

Can we also change 'Continuous Trading' here to just 'Continuous' as we don't need to duplicate the 'trading' that's in the header above?
image

> change the "State" column on the market list (both /markets and the switch market modal) so that it only shows market. market.tradingmode (and then show the trigger if monitoring auction) as above.

image

That could look like this:
image

Note, I've also changed the column heading there to 'Trading  mode' to match the market header.


On the warning below the ticket, the warning icon shrinks when it goes over more than one line, can we fix that please?
Also, the red bar should be the full height of the accompanying text block. It's currently a fixed height. 
image


I'm also not entirely sure what that warning is telling me - am I still able to place a limit order but not a market order? I did try reading the auction spec, but couldn't work this out. And if we're doing away with 'suspended' for the mode, maybe it should say 'in auction' here? @candida-d / @campbellssource 

If it's a warning rather than an error it should probably use the orange 'warning' intent rather than the red one.

**Comment by candida-d** [comment]
> I'm also not entirely sure what that warning is telling me - am I still able to place a limit order but not a market order? I did try reading the auction spec, but couldn't work this out. And if we're doing away with 'suspended' for the mode, maybe it should say 'in auction' here? 

@petewilliams I took it as the market would be in a liquidity monitoring auction and thus only accepts liquidity commitments, or liquidity provision orders, which I believe currently can’t be placed via the UI. https://github.com/vegaprotocol/specs/blob/master/protocol/0038-OLIQ-liquidity_provision_order_type.md#liquidity-provisioning-order-features

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (candida-d) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx]: @PeteWilliams Yeah that makes sense, I agree. I’ll suggest a change.

[the remark this answers is not in the document]
Comment (candida-d) [reply libs/orders/src/lib/order-hooks/use-order-validation.tsx]: @PeteWilliams Yeah that makes sense, I agree. I’ll suggest a change.

File: libs/orders/src/lib/order-hooks/use-order-validation.tsx [hunk 14]
```diff
@@ -64,41 +160,62 @@ export const useOrderValidation = ({
...
 
     if (
       fieldErrors?.size?.type === 'validate' &&
       fieldErrors?.size?.message === ERROR_SIZE_DECIMAL
     ) {
       if (market.positionDecimalPlaces === 0) {
-        return t('No decimal amounts allowed for this order');
+        return {
+          isDisabled: true,
+          message: t('No fractional amounts are allowed for this order'),
```
Comment (candida-d) [inline libs/orders/src/lib/order-hooks/use-order-validation.tsx:207]:
```suggestion
          message: t('Order sizes must be in whole numbers for this market'),
```
