### PR TITLE
Fix/1546 staking requests

### LINKED ISSUE #1546: Huge number of requests being made rapidly on staking page
## Description

This issue was discovered when staking tests were hanging due to Chrome crashing in CI. 

## Steps to Reproduce

1. Go to Staking page
2. Connect Vegawallet
3. Requests getting sent rapidly 

On Testnet around 1000 requests are getting sent a minute and seems to be even more on local instance of Vegacapsule where the epoch is set to 5 seconds. 

## Screenshots

More info can be found in this Slack thread: 
https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1664460708017719

## Device details

Tested on Chrome connected to Testnet, Stagnet 3 and Capsule

### PR DESCRIPTION
**Pull request by dexturr**
# Related issues 🔗

Closes #1546 

# Description ℹ️

Fixes the unreasonable number of requests that were being sent from the staking page.

# Demo 📺

Screenshot 2022-10-14 at 12 22 33

# Technical 👨‍🔧

Data flow with containers was dodgey causing request loops. Sorting the data flow has vastly reduced the number of requests that were needed.

### CODE REVIEW

File: apps/token/src/routes/staking/node/node.tsx [hunk 1]
```diff
@@ -137,4 +128,8 @@ export const StakingNode = ({ data }: StakingNodeProps) => {
   );
 };
 
-export default StakingNodeContainer;
+export const Node = () => {
+  return (
+    <NodeContainer>{({ data }) => <StakingNode data={data} />}</NodeContainer>
```
Comment (sam-keen) [inline apps/token/src/routes/staking/node/node.tsx:133]: Question (blocking?): Intentional closing brace as the only content in the NodeContainer?

**Review by sam-keen — APPROVED** [review]
