### PR TITLE
Fix/1128: Individual proposal pages failing to load

### LINKED ISSUE #1128: Individual proposal pages failing to load
Screenshot 2022-08-24 at 09 46 52

### PR DESCRIPTION
**Pull request by sam-keen**
# Related issues 🔗

Closes #1128

# Description ℹ️

Ensures individual proposal pages are loading, based on the same data as the other proposal pages.

# Technical 👨‍🔧

Individual proposal pages were built early on and relied on the REST endpoint to get the 'terms' data. Fairground was broken for individual proposals because it didn't have an `NX_VEGA_REST` env var, and was (possibly?) using a cached version which pointed at a borked node. The cleanest solution IMO was to remove the unnecessary REST reliance, instead using GQL fully, bringing everything in line.

### CODE REVIEW

**Review by edd — APPROVED** [review]

File: apps/token/src/routes/governance/proposal/proposal-container.tsx [hunk 1]
```diff
@@ -36,16 +19,7 @@ export const PROPOSAL_QUERY = gql`
 `;
 
 export const ProposalContainer = () => {
-  const { t } = useTranslation();
   const params = useParams<{ proposalId: string }>();
-  const proposalUrl = React.useMemo(
-    () => new URL(`governance/proposal/${params.proposalId}`, ENV.restUrl).href,
```
Comment (notbot00) [inline apps/token/src/routes/governance/proposal/proposal-container.tsx:42]: chore (blocking?): i think it would be more future proof (well, less confusing in the future) if we'd remove this restUrl from the ENV object, and remove the whole `NX_VEGA_REST` from all the env files.

**Review by asiaznik — APPROVED** [review]

File: apps/token/src/routes/governance/proposal/proposal-container.tsx (hunk 1 above)
Comment (sam-keen) [reply apps/token/src/routes/governance/proposal/proposal-container.tsx:42]: The rest url still appears to be used in some circumstances. It goes beyond the reach of this quick-fix ticket. I'll make a separate ticket to go through and remove the env var where possible.
