### PR TITLE
fix(explorer): correctly display data source matches

### LINKED ISSUE #3333: numberDecimalPlaces is not included in Explorer Settlement oracle specification or Proposal governance page
## Description

Within a market proposals `dataSourceSpecForSettlementData` there is a key filter that specifies the number of decimals to send for settlement

```
 "key": {
"name": "prices.BTC.value",
 "type": "TYPE_INTEGER",
"numberDecimalPlaces": "5"
```
This is important since it is needed in order to know how to send the settlement price in terms of decimals. 
There seem to be no way to find it in proposal, console or explorer.

## Steps to Reproduce

1. Go to ['...'](https://validator-testnet.governance.vega.xyz/proposals/9ea36df2b16fc396c34c79843e9f47b21ebede726657d57bb59dffbcd4e2076b) or https://validator-testnet.explorer.vega.xyz/oracles/e385156c00669eca7a567bf0a038e6d035551569aaaa8dce58ef53f53a478a01
2. search for numberDecimalPlaces

## Expected behavior

numberDecimalPlaces should be available.

## Screenshots

Screenshot 2023-03-31 at 13 43 44
Screenshot 2023-03-31 at 13 43 12

### LINKED ISSUE #4553: Explorer Oracles display incorrectly shows no matched data
## Description

On mainnet (see https://github.com/vegaprotocol/vega/issues/9075 for why not testnet), where data has been submitted and matched filters, those filters still show no matched data. It's likely the query is incorrect, or they rely on the `updated` field which appears not to actually update when data is matched.

# Tasks
- [x] Ensure ✅ is shown when data matches
- [x] render data when it matches
- [x] Fix queries to use dataConenction if they are not

### PR DESCRIPTION
**Pull request by edd**
- fix(explorer): correctly select data
- fix(explorer): select decimalplaces on oracles

# Related issues 🔗

Closes #4553. Also closes #3333

# Description ℹ️

On Explorer's oracle listing page, each data source incorrectly showed a red cross for matched data, even if there had been submitted data. This was dixed by changing the query used to feed the data. As I was in there anyway, I also closed #3333. However the fix isn't very useful at the moment because the data node is returning incorrect data (see https://github.com/vegaprotocol/vega/issues/9206)

### CODE REVIEW

**Review by MadalinaRaicu — APPROVED** [review]

File: apps/explorer/src/app/routes/oracles/components/oracle-markets.tsx [hunk 1]
```diff
@@ -61,3 +55,14 @@ export function OracleMarkets({ id }: OracleMarketsProps) {
...
+
+export function getLabel(
+  id: string,
+  m: ExplorerOracleForMarketsMarketFragment | null
+): string {
+  const settlementId =
+    m?.tradableInstrument?.instrument?.product?.dataSourceSpecForSettlementData
+      ?.id || null;
+
+  return id === settlementId ? 'Settlement for' : 'Termination for';
```
Comment (MadalinaRaicu) [inline apps/explorer/src/app/routes/oracles/components/oracle-markets.tsx:67]: little note here: we're going to have 3 types of data source specs coming 
* settlement (future, perps)
* termination (futures)
* settlement schedule (perps)

**Review by MadalinaRaicu — APPROVED** [review]

**Review by guoguojin — APPROVED** [review]

File: apps/explorer/src/app/routes/oracles/components/oracle-markets.tsx (hunk 1 above)
Comment (edd) [reply apps/explorer/src/app/routes/oracles/components/oracle-markets.tsx:67]: Thanks for that. I'll make a ticket to fix this because it looks like it'll end up saying 'Termination for' for perps settlements 🤦
